### ISSUE TITLE
ContentUtils bulk update

### ISSUE THREAD

**Issue by Mitolius** [agrosner/DBFlow#1251]
DBFlow Version: 4.0.0-beta7
Issue Kind (Bug, Question, Feature): Question, Feature

Description: 

I'm working with ContentProvider (for SyncAdapter) and at some point in the code I need to update many rows. As there isn't ContentUtils.bulkUpdate() method, I try to replace it by:

```
OperatorGroup where = getBaseWhereClause();
where.andAll(getSyncTypeColumn().eq(type), getSyncStatusColumn().in(STATUS_PENDING, STATUS_RETRY));
SQLite.update(getModelClass())
                .set(getSyncStatusColumn().eq(STATUS_IN_PROGRESS))
                .where(where)
                .executeUpdateDelete();
```
It isn't working while other operations made by ContentUtils work fine (Cause of CotentProvider I guess). I also try to execute a simple select as following:

`SQLite.select().from(OrmAddressBook.class).where().queryList()`
return 0 row while 
`ContentUtils.queryList(OrmAddressBook.CONTENT_URI, OrmAddressBook.class,nonGroupingClause(),null)`
return all rows.

Is the problem come from ContentProvider ?

Is it planned to add a bulkUpdate() method to ContentUtils in the future ?

Thanks

**Comment by agrosner** [comment]
SQLite wrapper objects do not know about the associated content provider model system, and thus do not sync with a content provider. in terms of what is supported for `ContentProvider` , it does not support ` bulkUpdate`. SQL wrapper updates are real sql queries, which content providers do not support directly.
