### ISSUE TITLE
[Question] how use max or min inside where or having ?

### ISSUE THREAD

**Issue by xanscale** [agrosner/DBFlow#1398]
example SQL

`SELECT * FROM exampleTable GROUP BY exampleValue HAVING MIN(ROWID)`

the problem is that where and having require sqlcondition and not method

i don't know if this is the correct place to make that question

**Comment by agrosner** [comment]
not supported yet.

**Comment by agrosner** [comment]
it looks like SQLite supports having with only Conditions such that 
`SELECT * FROM exampleTable GROUP BY exampleValue HAVING MIN(ROWID) > ${someScalar}` Does that query work if you use the `StringQuery` class?

**Comment by xanscale** [comment]
the query i write works using SQLite directly and return 1 value for each distinct exampleValue choosing record with minimum ROWID for each exampleValue

**Comment by agrosner** [comment]
closing as SQLite doesnt support it, as it seems.
