### ISSUE TITLE
Old migrations may crash because of db changes in later db versions

### ISSUE THREAD

**Issue by pinpointdev** [agrosner/DBFlow#1409]
DBFlow Version: 4.0.5
Issue Kind (Bug, Question, Feature): Question

Description: 
- Say I have a model class called Stats.
- For db version 2 I have a migration that adjusts ColumnA in the Stats table. I can't use UpdateTableMigration because it requires a per-row calculation to determine what the new value of ColumnA should be. So I'm forced to queryList on the Stats table, iterate through all of the Stats rows and call Stats.save() once the new value for ColumnA is set.
- For db version 3, I add a new column, ColumnB to the Stats table. I use an AlterTableMigration to do this.
- Say a user never upgrades to the app version that has db version 2, and goes directly to version 3 from version 1. So the v2 migration, then the v3 migration both run after the app upgrade. When Stats.save() is called in the v2 migration, the app will crash because the Stats table has no ColumnB yet. There is only one version of the _Table classes, and in this version of the app that includes ColumnB, but the AlterTableMigration that adds ColumnB hasn't run yet.

This is the exception:
Fatal Exception: android.database.sqlite.SQLiteException: table Stats has no column named ColumnB (code 1): , while compiling: INSERT INTO `Stats`(`ColumnA`,`ColumnB`) VALUES (?,?)

It seems like all pending AlterTable migrations should be run first for all db versions before the other migrations run? Is there a workaround for this problem? Thanks!

**Comment by pinpointdev** [comment]
For now, I'm working around this by also adding an AlterTableMigration that adds columnB to the v2 migration. I thought this would cause a crash when it tries to add the column again when the v3 migration runs but it doesn't.

**Comment by agrosner** [comment]
for migrations you should avoid if you can reusing old classes in the migration. in 4.1.0 there will be a flag that lets you reuse old table classes. but once table changes code side, reading from those models becomes obsolete. best short-term solution is copy paste the old generated code into some file that you can reference in the migration.

**Comment by agrosner** [comment]
better to stick to raw SQLite queries for migrations rather than use DBFlow generated classes because of said changes to model classes and they will no longer be compatible.

**Comment by pinpointdev** [comment]
Thanks for the reply. Is there any reason my workaround is a bad idea? That is, just adding the columns in the old AlterTableMigration as well as the new one.

**Comment by pinpointdev** [comment]
It seems like adding a column that already exists does cause an exception on certain devices. I also can't just catch the exception because I can't override AlterTableMigration.migrate() to trap the exception because the method is final.

It seems like my 2 options are:
1. Copy the AlterTableMigration code into my own class and catch the exception that is thrown if the column already exists.
2. Use raw sql for all updates and inserts in migrations like you suggested. Is there a convenient way to generate these statements for my models?

Thanks for being so responsive.

**Comment by agrosner** [comment]
2. You could copy paste them, or even create separate model classes mirroring the existing code. there is a new feature in 4.2.4 (maybe earlier) that you can set `@Table(createWithDatabase = false)` which generates all the code you need, minus adding it to the DB. Set the table name same as old one, copy class fields that mirror old version, and then you can use it by reading directly from db as if it was a real table! :)
