### ISSUE TITLE
import/export database to and from sd card

### ISSUE THREAD

**Issue by VasilisKatsoris** [agrosner/DBFlow#1435]
I'm migrating to DBFlow and I have an option in my app where the user can create local backup of the databse and later restore everything to that state. I implement the export by copying the .db file to the specified location.

But I have problems with the import. Right now I copy the back up database file to the current databse location overwriting it. But this needs total app close in order for the changes to take effect doing:

android.os.Process.killProcess(android.os.Process.myPid())

I assume there must be a better way to do this. Can you direct me to a solution?

**Comment by agrosner** [comment]
this sounds like a question and not a bug or feature. As I wish to help with questions, a stackoverflow.com post might suffice here.
