### ISSUE TITLE
RX support for transactions

### ISSUE THREAD

**Issue by epetrenko** [agrosner/DBFlow#1442]
DBFlow Version: 4.1.1
Issue Kind (Bug, Question, Feature): Feature

Description: 
Currently we have reactive extensions for such things as `Queriable`, `ModelQueriable`, `ModelAdapter`. It would be nice to have a possibility to work with `ITransaction` in reactive way too.

**Comment by agrosner** [comment]
in `5.0` branch, you will be able to observe on the `DBTransactionQueue` via:
```
database.beginTransactionAsync { select from MyModel::class  }
  .asObservable()
  ..//etc
```

**Comment by agrosner** [comment]
also `ITransaction` will return a result on the execution, thus allowing you to evaluate that selection and subscribe to its completion:
```kotlin
database.beginTransactionAsync { select from MyModel::class  }
  .asObservable()
  .subscribe { list -> 

  }
```

**Comment by epetrenko** [comment]
Thanks a lot.

**Comment by agrosner** [comment]
5.0.0-alpha1 released!
