### ISSUE TITLE
Incorrect priority order for @Migration(version = , database =, priority =)

### ISSUE THREAD

**Issue by andery-konovalov** [agrosner/DBFlow#1467]
DBFlow Version: from 4.1.0
Issue Kind: Bug

Description: 

Incorrect priority for migration instructions for pre-generated <DBName>_Database class.
Now it have descending sorting for migration versions but priority sorts by ascending.
Seems, the error is here: https://github.com/Raizlabs/DBFlow/commit/624652b59d412cbee85cf985899269c2fe2fe5e9#diff-2cd09486436a5edd8e19761406af326f

Here is example of the 4 last lines from the <dbName>_Database generated class constructor:
    ...  
    addMigration(10, new Migration10RouteDropUniqueConstraint());
    addMigration(9, new Migration9TagAddDefaultValues()); //priority = 1
    addMigration(9, new Migration9PlaceTagAddColumns(model.PlaceTagPersistable.class)); //priority=2
    addMigration(9, new Migration9RouteTagAddColumns(model.RouteTagPersistable.class));//priority = 2
  }
1) In 4.1.0 and later addMigration instruction are sorted by db version number.
2) last 3 instructions with db version 9 have incorrect order and instruction with priority 1 should be the last. (Now it tries to change default values before the column adding)

Please check. Thank you!

**Comment by DanicMa** [comment]
Having the same issue on v 4.2.4.

Can you elaborate if ascending order (1 = highest priority and 99 = lowest priority) will be used from now on? If so, would it be possible to update the documentation accordingly?

Thanks for your great work!

**Comment by kelsos** [comment]
Any clarification regarding this issue? Is this a bug? or an intended behaviour?

**Comment by agrosner** [comment]
It is a bug, that I shouldn't go back on - so it's in reverse order. Lower number priority is higher priority. Higher the number, the lower the priority. in `develop` the docs are updated.
