### ISSUE TITLE
Gradle can not finish syncing

### ISSUE THREAD

**Issue by knighthedspi** [agrosner/DBFlow#1508]
DBFlow Version: 4.2.4

Bug or Feature Request: Gradle can not finish syncing

Description:
Below is my gradle config

apply plugin: 'kotlin-kapt'
def dbflow_version = "4.2.4"
def sqlcipher_version = "3.5.7"
dependencies {
    kapt "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
    // sql-cipher database encryption (optional)
    implementation "com.github.Raizlabs.DBFlow:dbflow-sqlcipher:${dbflow_version}"
    implementation "net.zetetic:android-database-sqlcipher:${sqlcipher_version}@aar"
    // kotlin extensions
    implementation "com.github.Raizlabs.DBFlow:dbflow-kotlinextensions:${dbflow_version}"
}

When run on Android Studio 3.0.1 with gradle 4.1, gradle keep running as the below image and can not finish syncing
https://www.dropbox.com/s/673wp9n8ga4ikce/Screenshot%202018-01-09%2000.07.25.png?dl=0
Can you help me to fix this issue?
Thanks

**Comment by huytranrjc** [comment]
Same with #1509 , caused by dbflow-kotlinextensions resource not found error
https://jitpack.io/com/github/Raizlabs/dbflow/dbflow-kotlinextensions/4.2.4/dbflow-kotlinextensions-4.2.4-sources.jar (NOT FOUND,404)

**Comment by agrosner** [comment]
using lowercase `raizlabs` and `dbflow` should fix it. seems like a jitpack error.
