### ISSUE TITLE
update dbflow at runtime

### ISSUE THREAD

**Issue by omar-adel** [agrosner/DBFlow#1510]
I have 3 tables in one database 

shopping.db

product , favorite , download

but I may update this sqlite at runtime  
by downloading new sqlite file from internet 
which has only product table
so 

1 - how to update sqlite at runtime ?

2- if update possible , how to override migration methods
so I can restore all records in favourite and download tables in the new updated database ?

**Comment by d-rahul** [comment]
I have also same query

**Comment by agrosner** [comment]
runtime changes to dbflow are not supported. they must be bundled with the app ahead of time. You can read in the sqlite file and just execute those sqlite commands using `database.rawQuery()` on each, but if it alters your table structure, it may lead to app in inconsistent state.
