### ISSUE TITLE
Problems with the data integrity when querying DB during the transaction

### ISSUE THREAD

**Issue by mkoslacz** [agrosner/DBFlow#1512]
DBFlow Version: 4.2.4

Bug or Feature Request: Bug

Description:

In our app we use the mixed repository that merges the data from a cache, DBFlow and a remote. It returns mentioned contents in Rx stream as a sequence. Before returning the remote data the mixed repo replaces records in DB to keep the local storage up to date with the remote. Replacing is performed by deleting records from DB for given specification and then saving the data from the remote. We perform it this way to remove obsolete records that were deleted from the remote. Both operations, deleting and saving, are performed in the single transaction. Despite this, we are able to reproduce the scenario in which we read from DB between these operations, which results in obtaining empty results from database, because we hit the DB in the exact moment after deletion, and before saving the new data.

AFAIK queries performed during the transaction shall return the data snapshoted before the transaction start. Are there some special prerequisites that we should meet farther than just using the transaction? Sorry if I missed something that is already in docs.

I attach the gist that showcases the way we use transactions in our project. We use the presented method in the Rx stream from the remote. If you don't see any obvious problems in this code I can provide you a more detailed example.

https://gist.github.com/mkoslacz/ec39fefe5956a8fd1e9636ee0810d5d8

**Comment by agrosner** [comment]
you should have placed the queries on the db transaction queue, which orders them sequentially. I don't think this is a DBFlow bug, rather an implementation error. `executeTransaction()` runs query or db operations on current thread.
