### ISSUE TITLE
Undocumented change in FlowContentObserver

### ISSUE THREAD

**Issue by virusman** [agrosner/DBFlow#1513]
DBFlow Version: 4.2.4 (4.2.0+)
4.2.0 introduced a breaking change: FlowContentObserver requires a contentAuthority parameter that doesn't seem to be documented. The docs still suggest using it without parameters:
https://agrosner.gitbooks.io/dbflow/content/Observability.html
But that constructor doesn't exist anymore.

**Comment by theaircrasher** [comment]
I'm trying to upgrade to version 4.2.4 from version 4.1.2 and dealing with with the same issue. Is there any example or documentation available somewhere? Thanks in advance.

**Comment by hannesa2** [comment]
I run into a similar issue with Android O https://github.com/Raizlabs/DBFlow/issues/1523 here I was able to solve it

**Comment by raphaelbgr** [comment]
Still no fix for this? Unfortunatelly I'm dealing with an App wich uses DBFLow :(

**Comment by ubaierbhat** [comment]
As mentioned in  #1523 , declare the content provider in AndroidManifest.  

```xml        
<provider
            android:name="com.raizlabs.android.dbflow.runtime.StubContentProvider"
            android:authorities="${applicationId}"
            android:exported="false" />
```

And then set the content authority where ever you are creating a new instance of  FlowContentObserver

```java
observer = new FlowContentObserver(BuildConfig.APPLICATION_ID);
```
