### ISSUE TITLE
Error in FlowContentObserver.onChange

### ISSUE THREAD

**Issue by julienmeyer** [agrosner/DBFlow#1529]
DBFlow Version: 4.2.4

Bug or Feature Request: 
Bug or bad use

Description:
I got an error in the method "onChange" from the class FlowContentObserver  because the queryNames from the uri is empty [see code](https://github.com/Raizlabs/DBFlow/blob/966a9ad7d4ab6c1ef20572c16bb06c4e4b608e71/dbflow/src/main/java/com/raizlabs/android/dbflow/runtime/FlowContentObserver.java#L266) I don't really know if it's normal or not to have queryNames empty but you try to create an array before checking if the queryNames is empty.

I can create a PR to solve this problem but can you confirm me that queryNames could be empty ?

**Comment by agrosner** [comment]
this bug was fixed in 5.0.0-alpha1, sorry for late response...
