### ISSUE TITLE
renameFrom in AlterTableMigration is giving an SQLiteException

### ISSUE THREAD

**Issue by aiavci** [agrosner/DBFlow#1537]
**DBFlow Version:** 4.1.2

**Bug or Feature Request:**
 renameFrom is causing exception in basic application.

Link for code before migration: [Before Migration](https://github.com/aiavci/myNotes)
Link for code after migration: [After Migration
](https://github.com/aiavci/myNotes/tree/DBFlow-Experiment)

**Description:**

Following error received when running renameFrom:
`android.database.sqlite.SQLiteException: there is already another table or index with this name: DiaryLogEntry (code 1): , while compiling: ALTER TABLE 'LogEntry' RENAME TO 'DiaryLogEntry'`

**_Relevant code below or in the Github link provided_**
_Database Before Migration_
```
@Database(name = MainDB.NAME, version = MainDB.VERSION)
object MainDB {
    const val NAME = "MainDB"
    const val VERSION = 1
}
```

_Table Before Migration_
```
@Table(database = MainDB::class, allFields = true)
class LogEntry {

    @PrimaryKey
    lateinit var entryId: String

    lateinit var entryTitle: String
}
```

_Database After Migration_
```
@Database(name = MainDB.NAME, version = MainDB.VERSION)
object MainDB {
    const val NAME = "MainDB"
    const val VERSION = 2
}

@Migration(version = MainDB.VERSION, database = MainDB::class)
internal class MainDBMigration1 : AlterTableMigration<DiaryLogEntry>((DiaryLogEntry::class.java)) {

    init {
        renameFrom("LogEntry")
        Timber.d("New name given to LogEntry. It is now DiaryLogEntry.")
    }
}
```

_Table After Migration_
```
@Table(database = MainDB::class, name = "DiaryLogEntry", allFields = true)
class DiaryLogEntry {

    @PrimaryKey
    lateinit var entryId: String

    lateinit var entryTitle: String
}
```

**Comment by theaircrasher** [comment]
I am dealing with the same problem. Basically DBFlow adds new Tables in onUpgrade . As we need to change the table name in the Class representing the Table DBFlow sees this class as a new table entry and creates a new table. That is why the rename failing.

The rename has to take place before DBFLow checks for new tables. However I haven yet found  a way to achieve that.

**Comment by agrosner** [comment]
I see what you mean. the tables are created pre-migrations. as of 5.0.0-alpha1 it is not correct. One thing you could do is:
1. make a dummy table that contains old name and proper fields
2. Create rename migration
3. Make a `@Table(createWithDatabase = false)` mirroring said table that has the new name.
that should fix your issue, even though its not ideal. I will think of a better mechanism.

**Comment by theaircrasher** [comment]
Thanks, for your tip. I will try that.

**Comment by agrosner** [comment]
Note it might have issues on new installs, so its not perfect.

**Comment by T-mans** [comment]
> Note it might have issues on new installs, so its not perfect.

I am using version 4.2.4(because I failed to include 5.0.1alpha),and I got the same problem.
I think this is a issue which need to be fixed.
now, we can do like this:
1. create new table
2. copy data from old to new
3. delete old table

**Comment by Benyuss** [comment]
Any progress on this?
