### ISSUE TITLE
Query is slow for 8 rows

### ISSUE THREAD

**Issue by lukewaggoner-zz** [agrosner/DBFlow#1543]
DBFlow Version: 4.1.2

Bug or Feature Request: Query is ridiculously slow

Description: I'm querying a table (5 columns, String, Int, String, Boolean, Long) for all rows (only 8-10 exist in the table), and the query is taking 1sec+. Another query of a table with 100+ rows takes ~150ms to return 50 rows with 6 columns, including a stubbed foreign relationship. I'm wondering why the first query takes so incredibly wrong when it's returning a relatively minuscule amount of data.

**Comment by agrosner** [comment]
are you writing to the DB at the same time potentially?

**Comment by agrosner** [comment]
its tough to tell without more information. its possible the DB is locked due to a write somewhere else.

**Comment by lukewaggoner** [comment]
That's possible, although I don't know where it would be occurring. Are there any log statements that could shed some light on when it is being written to?

**Comment by agrosner** [comment]
There is a `FlowLog` you can set to different levels.
