### ISSUE TITLE
Inserting "?" as Text in column not working.

### ISSUE THREAD

**Issue by SyedaZunaira** [agrosner/DBFlow#1547]
DBFlow Version: 4.2.2

Bug or Feature Request: Inserting "?" as Text in the column not working.

Description: When I try to add "?" on a text filed it results in adding a NULL instead of "?" the query that formed in the back is something like `INSERT INTO `Message`(`MessageText`) VALUES(?)`
where it should be `INSERT INTO `Message`(`MessageText`) VALUES("?")` it is working perfectly for string other than "?"

**Comment by agrosner** [comment]
This requires a breaking change since "?" are treated same as `Property.WILDCARD`. Now you must specify `Property.WILDCARD` if you wanted `VALUES(?)`. Now using `"?"` turns it into `VALUES('?')`.

**Comment by agrosner** [comment]
in `develop`.
