### ISSUE TITLE
Does not support insertOrThrow()

### ISSUE THREAD

**Issue by ant-g** [agrosner/DBFlow#1551]
DBFlow Version:
I am working on a project using an older version 4.0.0-beta2, although I need to update this due to the changes to anntationProcessor which I am working on; I'm new to Android development.
However a search suggest that the latest version of BaseModel does not support this either.

Bug or Feature Request:
Strictly speaking a feature request, but I think a pretty key one

Description:
Provide a function to call insertOrThrow() which is required to try..catch a constraint failure (when we don't care about certain constraint failures)

Current code:
```
try{
    model.insert()
}catch(SQLLiteConstraintException e){
    // Does not catch
}
```
requires:
```
try{
    model.insertOrThrow()
}catch(SQLLiteConstraintException e){
    // Should catch
}
```

**Comment by agrosner** [comment]
so returning `-1` is not sufficient to know if an insert succeeds? or wrapping in a try catch is not enough? Im confused on why it's necessary. Also the construct we're building off of (`SQLiteStatement`), `returns the row ID of the last row inserted, if this insert is successful. -1 otherwise.` you could even make your own extension on `Any` or `BaseModel` for it:
```kotlin
@Throws(SQLLiteContraintException::class)
fun Any.insertOrThrow()   {
  val num = insert()
  if (num == -1) throw SQLLiteConstraintException("Insert failed")
}
```

**Comment by ant-g** [comment]
In the end I approached the problem differently (by using the built in model .save() which arguably was the right way to do what the code was trying to achieve).

However, the problem as I recall (this was some time ago) was that the code was failing; so not returning with anything, -1 or otherwise, but not `throwing` a `catch-able` exception.  

Forgive me as I am no Java expert, learning as I go, so I  am vague on how this is possible, however research at the time brought me [here](https://stackoverflow.com/questions/1375113/java-exception-not-caught), which seems to indicate that the internal function is not throwing a 'catch-able' exception but is causing an error none the less.  

> checked exceptions - they're the ones that you have to declare you'll throw, or catch if you call something that throws them.  

My assumption was that to get something that can be `caught` the call needs to be made to insertOrThrow() rather than just insert() (or why else have that function available?).

**Comment by agrosner** [comment]
Ah yeah `SQLLiteConstraintException` is probably called when `insert()` attempt to an already existing object. and yes `save()` is essentially `upsert()` or `insertOrUpdate()`
