### ISSUE TITLE
[kotlin] Could not find getter for private element

### ISSUE THREAD

**Issue by kenneth2008** [agrosner/DBFlow#1554]
DBFlow Version: 4.2.4
kotlin version: 1.2.31

Bug or Feature Request:
Since getter and setter for kotlin is auto generated. 
This guy say not found -> (dbflow.processor.ColumnValidator)

Description:
When using a Boolean Type with Uppercase field names, there will be an error message

Error message:
Could not find getter for private element: "MgtFee" from table class: Property. Consider adding a getter with name isMgtFee or making it more accessible.*==========*

I found that the solution is as the following, is it a bug?
@Column(getterName = "getMgtFee")
var MgtFee: Boolean = false

**Comment by krystiankaluzny** [comment]
Look at #1080
