### ISSUE TITLE
use Indexing failed !!!  logs: cannot use index 

### ISSUE THREAD

**Issue by BlueBirdCY** [agrosner/DBFlow#1555]
DBFlow Version: 4.2.4

Bug or Feature Request: bug ?  i don't know why... 

Description: copy the demo, index/indexGroups dosn't work. #**cannot use index**# 

![default](https://user-images.githubusercontent.com/7205639/38084291-e4859744-337e-11e8-8f73-72d05120e0c6.png)

![default](https://user-images.githubusercontent.com/7205639/38084508-b7721bd2-337f-11e8-9561-8d057a926f17.png)

![default](https://user-images.githubusercontent.com/7205639/38084480-a11820ca-337f-11e8-8134-a26f174066a5.png)

**Comment by agrosner** [comment]
did you enable the index? `Teacher_Table.firstIndex.enable()`?

**Comment by BlueBirdCY** [comment]
before use ：Teacher_Table.index_firstIndex.createIfNotExists();
it's done !
