### ISSUE TITLE
Can I still specify the database name in @Database after 4.1? 

### ISSUE THREAD

**Issue by qianshengta** [agrosner/DBFlow#1562]
DBFlow Version:
  v4.2.4

Bug or Feature Request: 
Can I still specify the database name in @Database after 4.1? 

Description:
Can I still specify the database name in @Database after 4.1? I like this way, especially in multiple database modules.
And how do I modify the database name before 4.1?

**Comment by agrosner** [comment]
yes you can. but its much more preferred using it on creation with the `DatabaseConfig` so you can have dynamic naming.

**Comment by agrosner** [comment]
pre 4.1 its probably not supported if I remember it was added in 4.1.

**Comment by qianshengta** [comment]
Thank you very much
