### ISSUE TITLE
Indicates whether the document is incorrect.?

### ISSUE THREAD

**Issue by qianshengta** [agrosner/DBFlow#1563]
DBFlow Version:   4.2.4

Bug or Feature Request:  Indicates whether the document is incorrect.

Description:  In the Query Models,
```
SQLite.select(EmployeeModel_Table.department,
                **Method.avg(EmployeeModel_Table.salary.as("average_salary")),  //This code error**
                EmployeeModel_Table.title)
      .from(EmployeeModel.class)
      .groupBy(EmployeeModel_Table.department, EmployeeModel_Table.title)
      .async()
      .queryResultCallback(new QueryTransaction.QueryResultCallback<EmployeeModel>() {
          @Override
          public void onQueryResult(QueryTransaction transaction, @NonNull CursorResult<EmployeeModel> tResult) {
              List<AverageSalary> queryModels = tResult.toCustomListClose(AverageSalary.class);

            // do something with the result
          }
      }).execute();
```

the error log is:
 android.database.sqlite.SQLiteException: near "AS": syntax error (code 1): , while compiling: SELECT `department`,AVG(`salary` AS `average_salary`),`title` FROM `EmployeeModel` GROUP BY `department`,`title`
if should it be:
Method.avg(EmployeeModel_Table.salary).as("average_salary")?????

**Comment by agrosner** [comment]
sounds like you got a syntax error from usage. this is a sqlite question, not a DBFlow question. my guess is you need to place the `AS` outside the `Method.avg()` like `Method.avg(EmployeeModel_Table.salary).as("average_salary")`
