### ISSUE TITLE
Better error message

### ISSUE THREAD

**Issue by douglasalipio** [agrosner/DBFlow#1567]
DBFlow Version: 4.2.4

Bug or Feature Request: Change an error message

Description:
When you create a data class with a default constructor and not initialize the parameters like this:
```
@Table(name = "standard", database = AppDatabase::class)
class Standard constructor(
        @PrimaryKey(autoincrement = true)
        @Column(name = "id")
        var id: Long,

        @Column(name = "question_text")
        var questionText: String) : BaseRXModel()
```

you'll get the message:
> e: error: *==========*class com.raizlabs.android.dbflow.processor.TableValidator :Table must provide a visible, default constructor.*==========*

But the problem isn't about providing a visibility for the constructor, the problem is set a default value for the parameters of the constructor as @agrosner mentioned in this [issue](https://github.com/Raizlabs/DBFlow/issues/1463)

**Comment by agrosner** [comment]
yes. dbflow does not yet support non-default constructors. this would be nice to implement, given time. I will look at other libraries and see how they solve this. It might require some significant changes to generated code as currently it direct assigns to an object.

**Comment by agrosner** [comment]
For now the message will change
