### ISSUE TITLE
how to solve multiple threads update value 

### ISSUE THREAD

**Issue by MichaelJokAr** [agrosner/DBFlow#1569]
DBFlow Version:
v4.2.4
Bug or Feature Request:
request
Description:
guys I meet a problem. when I update a value , I found it's sometimes not changed because I used multiple threads. But I can't remove the multiple threads. 
So how to solve this? when use multiple  threads. Thanks

**Comment by agrosner** [comment]
put everything in DB transactions. using `database.beginTransactionAsync {}` and callback into those threads when complete. This is more of a question than a bug or feature request, so closing :)
