### ISSUE TITLE
How must I save a BaseModel object class while BaseMigration is working?

### ISSUE THREAD

**Issue by confuste** [agrosner/DBFlow#1571]
Hello. I have the **4.1.1 DBFlow version**.

When my Android Application starts, it get some data of a server and update the information that was saved in the database. 
At the same time, I have a Migration class, that extends from BaseMigration. In the override migration method I copy some data from an old table to the new table. These tables won't be updated from the server. I do something like that:

`List<MyClassDBO> myClassDBOList = SQLite.select()
          .from(MyClassDBO.class)
          .queryList();`

After that, I analyze that list and then I make a new list which contains objects of the new table:

`List<MyNewClassDBO> myNewClassDBOList;`

At this time, I save "myNewClassDBOList" into the new table:

```
   private static void saveListReportContinueTo(List<? extends BaseModel> baseModelList, MyCallback myCallback) {

      FlowManager.getDatabase(MyDatabase.class)
          .beginTransactionAsync(new ProcessModelTransaction.Builder<>(
              new ProcessModelTransaction.ProcessModel<Model>() {
                @Override
                public void processModel(Model model, DatabaseWrapper d) {
                  model.save();
                }
              }).addAll(baseModelList).build())
          .error(new Transaction.Error() {
            @Override
            public void onError(Transaction transaction, Throwable error) {
              myCallback.onError();
            }
          })
          .success(new Transaction.Success() {
            @Override
            public void onSuccess(Transaction transaction) {

              myCallback.onSuccess();
            }
          })
          .build()
          .execute();
    }
```

The official documentation says:

> Prevent Recursive Access to the DB
> 
> Since Migration occur when the database is opening, we cannot recursively access the database object in our models, SQLite wrapper statements, and other classes in DBFlow that are inside a Migration.
> To remedy that, DBFlow comes with support to pass the DatabaseWrapper into almost all places that require it:
> 1. All query language BaseQueriable objects such as Select, Insert, Update, Delete, etc have methods that take in the DatabaseWrapper
> 2. Any subclass of BaseModel (Model does not provide the methods for simplicity)

I haven't understood that very well. Is the documentation saying that I must use the SQL queries and changing the original code?

Original:
```
@Override
 public void processModel(Model model, DatabaseWrapper d) {
model.save(); 
}
}).addAll(baseModelList).build())
```

New code?
```
@Override
 public void processModel(Model model, DatabaseWrapper d) {
// remove this line model.save(); 
d.query(... my sql query )
}
}).addAll(baseModelList).build())
```

And then, Must I change this code also and write a new code?

Original:
``List<MyClassDBO> myClassDBOList = SQLite.select()
          .from(MyClassDBO.class)
          .queryList();``

New code?

String [] columns = {"id", "title"};
`FlowCursor cursor = database.query("MyClassDBO", columns, null, null, null,null,null);`

Sorry for the issue but I have a lot of confusions about this topic. Thank you very much.

**Comment by agrosner** [comment]
in newer (or maybe that version) versions you can specify a `DatabaseWrapper` in the `save()`/`queryList()` call. 
Change: 
```
List<MyClassDBO> myClassDBOList = SQLite.select() .from(MyClassDBO.class) .queryList();
```
to:
```
List<MyClassDBO> myClassDBOList = SQLite.select() .from(MyClassDBO.class) .queryList(d);
```

And change:
```
model.save(); 
```
to:

```
model.save(d); 
```
