### ISSUE TITLE
How to update prepackaged database table contents,, Not schema !

### ISSUE THREAD

**Issue by Zakarya0001** [agrosner/DBFlow#1573]
Hi there,

I created an app that contains prepackaged database. At first time I inserted temp data so I can test the app, but when I inserted the real data and copied the new .db file to assets folder I found only the old temp data .

Please Help me. I only want to update the table contents not the structure .

**Comment by agrosner** [comment]
Please leave this for bug or feature requests. Insert real data post copying of the DB.
