### ISSUE TITLE
the function ContentUtils.buildUriWithAuthority usage?

### ISSUE THREAD

**Issue by YuPf1989** [agrosner/DBFlow#1575]
DBFlow Version:4.2.3

Bug or Feature Request:
 @ContentUri(path = NAME, type = ContentUri.ContentType.VND_MULTIPLE + NAME)
    public static final Uri CONTENT_URI = ContentUtils.buildUriWithAuthority(MyDatabase.AUTHORITY);

Description:
why the value CONTENT_URI don't containt path?or it just this?  And what is it different from ContentUtils.buildUri()? I think the method ContentUtils.buildUri override the path...

**Comment by agrosner** [comment]
`buildUri` is a base method that lets you specify a `baseContentUri` typically `content://` and `authority` is typically the application's content provider.
