### ISSUE TITLE
FlowManager.getDatabase(Database.class).executeTransaction(ITransaction) leads to CRUD ANR

### ISSUE THREAD

**Issue by laycui** [agrosner/DBFlow#1577]
DBFlow Version: 4.2.4

Bug or Feature Request:
Bug

Description:
When running the batch operation using
FlowManager.getDatabase(Database.class).executeTransaction(ITransaction)

It leads to the stuck of other SQLite.select().from().query() operations which are directly running without the wrapping of a transaction. Thus ANR happens.

Is this a known bug or something wrong causes this issue?
Thanks,

**Comment by laycui** [comment]
The issue raised up here is that in DbFlow 3.0.0-beta5, we use method
`TransactionManager.transact(Database.NAME, Runnable);`
to handle the DB transaction, and it works quite well;

But in DbFlow 4.2.4, if we use the equivalent method:
`FlowManager.getDatabase(AppDatabase.class).executeTransaction(ITransaction);`
it blocks the DB and make other DB operations happening on main thread lead to ANR.

So, I'd like to know what is the best replacement? Thanks.

**Comment by agrosner** [comment]
```
database.beginTransactionAsync()
..
.build()
.execute()
```
sorry for the late response...https://dbflow.gitbook.io/dbflow/usage2/usage/storingdata#async-transactions

**Comment by agrosner** [comment]
Added `@WorkerThread` annotation to that method for `5.0.0-alpha2`
