### ISSUE TITLE
Kotlin + extension not known

### ISSUE THREAD

**Issue by hannesa2** [agrosner/DBFlow#1579]
DBFlow Version: 4.2.4

Bug: Kotlin + extension are not known

Description:
Following https://agrosner.gitbooks.io/dbflow/content/RXJavaSupport.html
```
  compile "com.github.Raizlabs.DBFlow:dbflow-rx2:${dbflow_version}"
  compile "com.github.Raizlabs.DBFlow:dbflow-rx2-kotlinextensions:${dbflow_version}"

```
but `select` is not known
 ```
 select.from(MyTable::class.java)
  .rx()
  .list { list ->

  }
```
any ideas ?

**Comment by pokk** [comment]
You should add those libraries into the android module.
