### ISSUE TITLE
Observable for Table Changes

### ISSUE THREAD

**Issue by Wrakor** [agrosner/DBFlow#1583]
DBFlow Version: 4.2.4

Feature Request: Observable that emits once per database transaction.

Description: Currently, if I insert 20 items (even in the same transaction) the observable is emitting 20 times. I would like an option so that the observable only emits once per table change/transaction.

This is what I'm doing:
`(select from Offer::class where (Offer_Table.exclusive.eq(exclusive))).rx().tableChanges.map { it.list }.toObservable()`

**Comment by agrosner** [comment]
Its solved! in 5.0.0+

**Comment by agrosner** [comment]
https://dbflow.gitbook.io/dbflow/v/develop/usage2/usage/observability#tableobserver you can use RX, coroutines, paging or livedata
