### ISSUE TITLE
Delete object without clearing id and OneToMany

### ISSUE THREAD

**Issue by esscheffer** [agrosner/DBFlow#1585]
DBFlow Version:
4.2.4

Bug or Feature Request:
Delete object without clearing id and OneToMany

Description:
I have this 2 classes:

```
@Parcelize
@Table(database = AppDatabase::class, allFields = true)
data class Movie(@PrimaryKey(autoincrement = true) var databaseId: Long = 0,
                 var name: String = "",
                 var title: String = "") : Parcelable, BaseModel() {
    @get:OneToMany(methods = [(OneToMany.Method.ALL)])
    var trailers by oneToMany {
        select from Trailer::class where (Trailer_Table.movie_databaseId eq databaseId)
    }

    override fun save(): Boolean {
        trailers?.forEach { it.movie = this }
        return super.save()
    }
}
```

```
@Parcelize
@Table(database = AppDatabase::class, allFields = true)
data class Trailer(@PrimaryKey(autoincrement = true) var databaseId: Long = 0,
                   var name: String = "",
                   @ForeignKey(stubbedRelationship = true, onDelete = ForeignKeyAction.CASCADE)
                   var movie: Movie? = null
) : Parcelable, BaseModel()
```

Overriding save on `Movie` I was able to ensure that the save on a `Movie` will make the cascade save on a `Trailer` to save the trailers with the correct reference to `Movie`. The delete cascade also works; deleting a `Movie` delete all trailers it has. The problem is: it also sets the id (the field marked with `@PrimaryKey`) to 0 and sets the `OneToMany` relation list to null. Is it possible to do myself (like overriding delete myself or some configuration I'm not aware of) or to implement in the future to make the delete operation only remove the database entry without altering the object?

**Comment by agrosner** [comment]
The only way to implement your own extension on `ModelSaver` and providing one in the table config for the object via 

```kotlin
FlowManager.init(FlowConfig.builder(context)
.database(DatabaseConfig.builder(TestDatabase::class.java)
.addTableConfig(TableConfig.Builder(SimpleModel::class.java)
                    .modelAdapterModelSaver(modelSaver)
                    .build())
```
