### ISSUE TITLE
Sqlite ReadOnlyException (sqlite code 1032)

### ISSUE THREAD

**Issue by whao189** [agrosner/DBFlow#1587]
DBFlow Version:
3.0.0
Bug or Feature Request:
Description:
copy database file , from assets to  app's databases folder. then app open it , read data its ok, when open transaction , like this : 
 `
ITransaction xx = FastStoreModelTransaction.updateBuilder(xxModel);
FlowManager.getDatabase(aa.class).executeTransaction(xx);
`
throw exception .

Have anyone come across ????

**Comment by agrosner** [comment]
seems like a question and not a bug from DBFlow. This should be posted on stackoverflow.com
