### ISSUE TITLE
How does DBFlow customize database save addresses?

### ISSUE THREAD

**Issue by MORERICEMORE** [agrosner/DBFlow#1588]
DBFlow Version:4.2.4

Bug or Feature Request:

Description:
The database needs to be initialized on the SDCard

**Comment by agrosner** [comment]
if `SQLiteOpenHelper` does not support external file. then you can try making your own implementation of `OpenHelper` which could potentially place it on the SD card. this should help you here: https://stackoverflow.com/a/9168969/3911006
and https://dbflow.gitbook.io/dbflow/usage2/usage/databases#custom-flowsqliteopenhelper
