### ISSUE TITLE
No documentaton about addForeignKeyColumn

### ISSUE THREAD

**Issue by Rufim** [agrosner/DBFlow#1589]
DBFlow Version: 4.11

Bug or Feature Request: Feature

Description:
In cuurent wiki  or searching this repo i canot faind smallest example about right way to use 
addForeignKeyColumn(/* OK its clear that i should use same type as key */, 
/* And there we already has questions. what should i put there? 
    If in class i add Field @ForeginKey Foo bar; and it has column String id;
    bar? bar_id? Foo_Table.bar_id.getNameAlias().nameRaw()?
*/, 
/* 
 Same here not clear without spending time to try and right approach also unclear
 "$Foo_id" ?
 FlowManager.getTableName(Foo.class) + "id" ?
something else?
*/);

**Comment by agrosner** [comment]
```addForeignKeyColumn(SQLiteType.$, "columnName", "ReferencedTable(`column`)")```. Its just creating a Foreign key clause for you. https://www.sqlite.org/foreignkeys.html
