### ISSUE TITLE
Insert statement primary key binding wrong

### ISSUE THREAD

**Issue by bnsantos** [agrosner/DBFlow#1590]
DBFlow Version: 4.2.4

Bug or Feature Request: Not sure

Description: 
With those models

```java
@Table(database = AppDatabase.class)
public class Owner extends BaseModel {
    @PrimaryKey(autoincrement = true)
    private int id;
    @Column
    private String name;
    ....
}
@Table(database = AppDatabase.class)
public class Dog extends BaseModel {
    @ForeignKey(onDelete = ForeignKeyAction.CASCADE, stubbedRelationship = true)
    private Owner owner;
    @PrimaryKey(autoincrement = true)
    private int id;
    @Column
    private String name;
    ......
}
```

The generated `Dog_Table` have their insert statement with the columns pretty much in the order that they're in the file

```sql
INSERT INTO `Dog`(`owner_id`,`id`,`name`) VALUES (?,?,?)
```

when the first column is not the primary key the binding of the values can go wrong because of the generated `Dog_Table.bindToStatement`
```java
@Override
public final void bindToStatement(DatabaseStatement statement, Owner model) {
  int start = 0;
  statement.bindLong(1 + start, model.getId());
  bindToInsertStatement(statement, model, 1);
}
```

That way the value that is binded for the FK is actually the PK for this model.

I'm not sure if this is a bug or not. Usually my models have their primary keys on top but there was one model that had the FK before its PK, that's why I've stumbled upon this issue.

Is it interesting to add a sorting for columns during the annotation processing to avoid this? (I can work on that) Or should I make sure every model has their PK on top?

Thanks

**Comment by agrosner** [comment]
in `develop`. We were always putting the primary key autoincrement first due to outdated code. in 5.0.0 we actually generate both methods like:
```

  @Override
  public final void bindToInsertStatement(DatabaseStatement statement, Dog model) {
    if (model.getOwner() != null) {
      statement.bindLong(1, model.getOwner().getId());
    } else {
      statement.bindNull(1);
    }
    statement.bindLong(2, model.getId());
    statement.bindStringOrNull(3, model.getName());
  }

  @Override
  public final void bindToUpdateStatement(DatabaseStatement statement, Dog model) {
    if (model.getOwner() != null) {
      statement.bindLong(1, model.getOwner().getId());
    } else {
      statement.bindNull(1);
    }
    statement.bindLong(2, model.getId());
    statement.bindStringOrNull(3, model.getName());
    statement.bindLong(4, model.getId());
  }
```
and in 5.0.0-alpha2, it will respect the order as described.
