### ISSUE TITLE
ROWID auto increment in Kotlin

### ISSUE THREAD

**Issue by ayanyev** [agrosner/DBFlow#1593]
DBFlow Version: 4.2.4

Bug or Feature Request:
Primary key with **_rowId=true_** does not increment in Kotlin leading to a single record in table

Description:
Primary key with **_rowId=true_** has to have default value in Kotlin constructor. If it hasn't I get an exception saying that I need to have valid, visible constructor. If default value is present, there is only one record in table because rowId is not incremented and equals to the default value

**Comment by agrosner** [comment]
rowId doesn't auto-increment. 
in the docs:
```
/**
         * Specifies the column to be treated as a ROWID but is not an [.autoincrement]. This
         * overrides [.autoincrement] and is mutually exclusive.
         */
```

**Comment by agrosner** [comment]
https://stackoverflow.com/a/38290195/3911006
