### ISSUE TITLE
Observe table change not working on delete

### ISSUE THREAD

**Issue by esscheffer** [agrosner/DBFlow#1594]
DBFlow Version:
4.2.4

Bug or Feature Request:
Observe table change not working on delete

Description:
Given this code:
```
select.from(GameDBModel::class.java).rx().tableChanges.map { it.list }
    .toObservable().subscribe { games ->
        Log.i(TAG, "rx list: ${games.size}")
    }
```
To observe a table change with RxJava, the code is fired 2 times on an insert on the table and none on a delete. Is this a bug or I'm doing something wrong?

**Comment by Nailik** [comment]
I have exactly the same Problem. I fixed it by calling
`DirectModelNotifier.get().notifyTableChanged(Class.class, Action.DELETE);`
The best thing here would to make a parent class, notifing ...
I don't think this will be fixed at any time. 
In the new version (that's in beta) it uses LiveData, so now more usage for this - but all in all i think DBFlow is not being maintained anymore ...

**Comment by agrosner** [comment]
probably a bug. In 5.0.0+ we rework the query table system so that it only fires once per table per transaction on a query:
```kotlin
(select from GameDBModel::class).asFlowable { db -> queryList(db) }
  .subscribe { games ->
        Log.i(TAG, "rx list: ${games.size}")
 }
```

**Comment by agrosner** [comment]
under the hood it uses a temporary table to track changes on tables via triggers and checks after a transaction if they have changed, then dispatches updates to subscribers.
