### ISSUE TITLE
writes and transactions

### ISSUE THREAD

**Issue by nycodes9** [agrosner/DBFlow#1596]
DBFlow Version: 3.0.0 and above (checked till 4.2.4)

Bug or Feature Request: db writes followed  by transactions causes deadlock
(more precisely **W/SQLiteConnectionPool: The connection pool for database '/data/user/0/dabasename.db' has been unable to grant a connection to thread 481 (ThreadName) with flags 0x2 for 150.024 seconds.**)

Description:  Repro steps
0. 1 database, 1 table, simple text and text cols
1. `writes()` - some small writes (I have tested with 100, 1000 writes in a loop)
2. `reads()` - read all rows at a time
3. `ExecutorService DB_EXECUTOR_SERVICE =  Executors.newFixedThreadPool(5)`  - all non ui thread from a thread pool of size 5 (tested with 2 - 10, pool of 1 thread works fine for obvious reasons)
4. `tnx()` - simple transaction with `read()` and `writes()` inside execute block()
5. so running `DB_EXECUTOR_SERVICE.execute(tnx())` followed by `DB_EXECUTOR_SERVICE.execute(writes())` (and also other way round) causes the  above mentioned connection pool error. 
6. It seems that, if there is

>  write operation inside a transaction then that is blocked by the write outside the transaction and they starve each other to deadlock

7. Double checked with raw sqlite implementation, the behavior is the same - 

> outside write() waits on write() inside transaction to finish then it completes, but **never deadlocks**
 
### DbFlow code 

```
void writes(int size) {
    Model model;
    Random rand = new Random();
    for (int i = 0; i < size; i++) {
      model = new Model();
      model.date = new Date();
      model.randInt = rand.nextInt();
      model.save();
    }
  }

```
```
void read() {
    SQLite.select().from(Model.class).queryList().size();
}
```
```
void tnx() {
    FlowManager.getDatabase(Database.class)
        .executeTransaction(
            new ITransaction() {
              @Override
              public void execute(DatabaseWrapper databaseWrapper) {
                write(WRITE_SMALL);
                read();
              }
            });
  }
```

```
@MainThread
onClick(){
    DB_EXECUTOR_SERVICE.execute(
                    new Runnable() {
                      @Override
                      public void run() {
                        tnx();
                      }
                    });
    DB_EXECUTOR_SERVICE.execute(
                    new Runnable() {
                      @Override
                      public void run() {
                        write();
                      }
                    });
}
```

**Comment by agrosner** [comment]
if its a raw sqlite issue, its a dbflow issue. What I recommend is using `Transaction` which run operations serially without blocking main thread or overloading the DB. https://dbflow.gitbook.io/dbflow/usage2/usage/storingdata#transactions
