### ISSUE TITLE
cannot access com.raizlabs.android.dbflow.structure.BaseModel 

### ISSUE THREAD

**Issue by yanyonghua** [agrosner/DBFlow#1597]
DBFlow Version:
4.2.4
Bug or Feature Request:
Compile a problem
Description:
When I compiled it, I found that I could not use this class.
this is my code：
![default](https://user-images.githubusercontent.com/22539945/41278768-4317082e-6e5d-11e8-8c7c-bead0a75103e.png)

Use it in this place：
![default](https://user-images.githubusercontent.com/22539945/41278901-a7614268-6e5d-11e8-88da-daea8e141e59.png)

problem：
cannot access com.raizlabs.android.dbflow.structure.BaseModel ？？？？why？

**Comment by carlosbrolo** [comment]
Have updated to Gradle 3? (latest android studio?)

**Comment by agrosner** [comment]
sounds like a dependency issue.

**Comment by yanyonghua** [comment]
OK

**Comment by booldplx** [comment]
兄弟 请问怎么解决的啊
