### ISSUE TITLE
No method for random query

### ISSUE THREAD

**Issue by arshad115** [agrosner/DBFlow#1608]
DBFlow Version: 4.2.4

Bug or Feature Request: Feature Request

Description:

DBFlow does not support random query. 

In SQLite I would simply write the query as:
```
select * from table_name ORDER BY RANDOM() LIMIT 1;
```

I couldn't find anything which is equivalent for it DBFlow.

**Comment by agrosner** [comment]
Did you try something like `.orderBy(Property<Any>(NameAlias.rawBuilder("Random()").build()))`?

**Comment by agrosner** [comment]
For now, use `orderBy(OrderBy.fromString("RANDOM()"))` sorry for late reply! I will add a new way in `5.0.0-alpha2`

**Comment by agrosner** [comment]
Now even better, `orderBy random` will work in kotlin. Java, use `.orderBy(Method.random)`!
