### ISSUE TITLE
Composite @PrimaryKey + @ForeignKey second level deep

### ISSUE THREAD

**Issue by Rufim** [agrosner/DBFlow#1609]
DBFlow Version:
4.2.3
Bug or Feature Request:
Bug
Description:
Recently I try to create folowing class references with kotlin

```
@Table(...)
class A(@PrimaryKey var id: Int = 0)

@Table(...)
class B(@PrimaryKey var number: Int = 0, @ForeignKey(stubbedRelationship = true) @PrimaryKey var a : A? = null)

```
And abouve code compiles well as it should. All happy. But when i try to add next class

```
@Table(...)
class C(@PrimaryKey var number: Int = 0, @ForeignKey(stubbedRelationship = true) @PrimaryKey var b : B? = null)
```

it cause strange exeption when i try to comlile project:
> [kapt] An exception occurred: java.lang.IllegalArgumentException: Cannot map com.mycompany.project.models.A to a SQLite Type. If this is a TypeConverter, ensure it maps to a primitive type.

That strange because when i delete PK annotation all work OK again.
Maybe such referecnces is not supported? Or i miss something?

Also if i replace B FK referwnce with something like that:

```
@Table(database = FitcoolDatabase::class)
data class B(@PrimaryKey var number: Int = 0) {
    @ForeignKey(tableClass = A::class, references = [ForeignKeyReference(columnName = "aId", foreignKeyColumnName = "id")])
    @PrimaryKey
    var aId : Int? = null
}
```
All work OK again 

Also please not that if list varable starts with "set" like
```
    @get:OneToMany(methods = arrayOf(OneToMany.Method.ALL))
    var setList by oneToMany { (select from Set::class
            where (Set_Table.exercise_index.eq(index)) and (Set_Table.exercise_training_id.eq(trainingId))
            orderBy (Set_Table.index.asc())) }
```
It will not be found with error:
e: error: *==========*class com.raizlabs.android.dbflow.processor.definition.OneToManyDefinition :@OneToMany definition getSetList Cannot find referenced variable setList.*==========*

Upd:

Seems update(save) operation also not work with such key, When i try to save C class it will end with error like that. 
SQLiteLog: (1) near ",": syntax error when getUpdateStatement called with next SQL 
UPDATE OR REPLACE `C` SET `b_aId`=?,`b_number`=?,`number`=? WHERE `b_aId`=?,`b_number`=? AND `number`=?

**Comment by agrosner** [comment]
Nested foreign key refs are not currently supported. As for the second one, you should have filed a second issue, since theyre not related. For (2) if you change name to `listOfSet` or something like that, itll work. It seems like its a bug with things starting with `set`.

**Comment by agrosner** [comment]
in `develop` will be in `5.0.0-alpha2`.

**Comment by agrosner** [comment]
for (2). (1) is not supported yet.
