### ISSUE TITLE
For operations like Increase, Delete, and Update, is there a way to batch a List instead of iterating through it

### ISSUE THREAD

**Issue by qianshengta** [agrosner/DBFlow#1610]
DBFlow Version:  4.2.4

Bug or Feature Request:

For operations like Increase, Delete, and Update, is there a way to batch a List instead of iterating through it

Description:
For operations like Increase, Delete, and Update, is there a way to batch a List instead of iterating through it

**Comment by agrosner** [comment]
yeah. https://dbflow.gitbook.io/dbflow/usage2/usage/storingdata#faststoremodeltransaction this is a question. I'd like to leave issues for bug or feature requests. If there's something missing in the docs, please file an issue.
