### ISSUE TITLE
AndroidStudio3.1.3无法找到注解处理器

### ISSUE THREAD

**Issue by kakaxicm** [agrosner/DBFlow#1613]
DBFlow Version:4.2.4

Bug or Feature Request:Could not resolve com.github.Raizlabs.DBFlow:dbflow-processor:4.1.2.

Description:确定没有使用离线模式，
//编译和gradle工具版本:
buildToolsVersion '27.0.3' 
compileSdkVersion 27

//主模块gradle配置如下:
def dbflow_version = "4.2.4"
dependencies {
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
}
运行工程，错误信息如下:
======================
Could not resolve all files for configuration ':factory:debugAnnotationProcessorClasspath'.
> Could not resolve com.github.Raizlabs.DBFlow:dbflow-processor:4.2.4.
  Required by:
      project :factory
   > No cached version of com.github.Raizlabs.DBFlow:dbflow-processor:4.2.4 available for offline mode.
   > No cached version of com.github.Raizlabs.DBFlow:dbflow-processor:4.2.4 available for offline mode.
======================
之前集成butterknife也产生了类似的问题，降低版本解决了类似问题,求解对DBFlow怎配置才能成功编译运行？

**Comment by agrosner** [comment]
You are in offline mode.

**Comment by agrosner** [comment]
```
No cached version of com.github.Raizlabs.DBFlow:dbflow-processor:4.2.4 available for offline mode.
```
