### ISSUE TITLE
Cert https://agrosner.gitbooks.io/dbflow/content/ has expired

### ISSUE THREAD

**Issue by eku** [agrosner/DBFlow#1614]
Das Zertifikat ist am 9. September 2018, 12:05:00 GMT+2 abgelaufen.
Die aktuelle Zeit ist 9. September 2018, 19:24. 

Fehlercode: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by hannesa2** [comment]
btw @agrosner seams to have no interest anymore since end 2017
Everyone should make his own follow up task about this knowledge

<img width="305" alt="image" src="https://user-images.githubusercontent.com/3314607/45267118-be780280-b466-11e8-8c91-f121d37144e5.png">

**Comment by carmas123** [comment]
I think that this library is replace by Android Room :)

**Comment by aiavci** [comment]
carmas123, Room has some limitations, such as encryption

**Comment by hannesa2** [comment]
We use for encryption this https://github.com/commonsguy/cwac-saferoom in production, it's based on Room

**Comment by aiavci** [comment]
hannesa2, This library is not ready for production just yet. The developers are experimenting with it.

**Comment by agrosner** [comment]
https://dbflow.gitbook.io/dbflow/usage2 :) try this one.
