### ISSUE TITLE
Gradle build failed for native (C library) library creation task with NullPointerException

### ISSUE THREAD

**Issue by gauravnshah** [agrosner/DBFlow#1615]
DBFlow Version:
./gradlew  native_codeSharedLibrary

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileNative_codeSharedLibraryNative_codeC'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

Bug or Feature Request:

Description:
Gardle native build fails

**Comment by agrosner** [comment]
this does not seem like a dbflow issue. Not sure without more information. closing.
