### ISSUE TITLE
Support for LiveData

### ISSUE THREAD

**Issue by aiavci** [agrosner/DBFlow#1617]
### DBFlow Version:
4.2.4

### Bug or Feature Request:
Support for [LiveData](https://developer.android.com/topic/libraries/architecture/livedata)

### Description:
It would be great to have support for LiveData out of the box.

Currently, The RxJava submodule is one way to keep any LiveData objects observable. @agrosner has provided a [tutorial](https://medium.com/fuzz/how-to-make-dbflow-as-testable-as-room-with-kotlin-b1694f3f80ad) on how to implement this. However, a new submodule with LiveData support out-of-the-box would be great.

**Comment by agrosner** [comment]
in `develop` :)!!! https://github.com/agrosner/DBFlow/blob/develop/usage2/livedata.md
