### ISSUE TITLE
Across different modules, Table xxx needs to define at least one primary key

### ISSUE THREAD

**Issue by wangsuicheng** [agrosner/DBFlow#1619]
DBFlow Version:
4.2.2
Bug or Feature Request:
class com.raizlabs.android.dbflow.processor.TableValidator (Kotlin reflection is not available) :Table xxxx needs to define at least one primary key
Description:
I have the 
```
public class BaseModelData like {
    @Column
    @PrimaryKey(autoincrement = true)
    @Index
    private long id;
}
```
 in the base-module, if I have the other library-module dependend on the base-module,
and add table like TestTable extends BaseModelData, when build, has failure above

**Comment by agrosner** [comment]
Cross module subclasses are not supported. You need to keep it in the same module.

**Comment by agrosner** [comment]
you can use `inheritedFields` on subclasses to utilize the fields if you need to share.
