### ISSUE TITLE
Make project fail: must be a visible abstract class

### ISSUE THREAD

**Issue by lhy6962** [agrosner/DBFlow#1627]
DBFlow Version: 5.0.0-alpha1

Bug or Feature Request: build fail
When I Click "Make Project" then shows the log below:

> *==========* :com.example.monkey.xposedhookdemo.TestDataBase must be a visible abstract class that extends com.dbflow5.config.DBFlowDatabase*==========*
错误: java.lang.Thread.getStackTrace(Thread.java:1552)
错误: com.dbflow5.processor.ProcessorManager.logError(ProcessorManager.kt:212)
错误: com.dbflow5.processor.ProcessorManager.logError(ProcessorManager.kt:219)
错误: com.dbflow5.processor.definition.DatabaseDefinition.<init>(DatabaseDefinition.kt:82)
错误: com.dbflow5.processor.DatabaseHandler.onProcessElement(Handlers.kt:229)
错误: com.dbflow5.processor.BaseContainerHandler.handle(Handlers.kt:194)
错误: com.dbflow5.processor.ProcessorManager.handle(ProcessorManager.kt:233)
错误: com.dbflow5.processor.DBFlowProcessor.process(DBFlowProcessor.kt:67)

My Code:
`@Database(name = TestDataBase.NAME, version = TestDataBase.VERSION)
public class TestDataBase {

    //数据库名称
    public static final String NAME = "MyDatabase";
    //数据库版本号
    public static final int VERSION = 1;
}`

**Comment by agrosner** [comment]
```
========== :com.example.monkey.xposedhookdemo.TestDataBase must be a visible abstract class that extends com.dbflow5.config.DBFlowDatabase*==========*
```
yes this is the message. you have to change your db from
```
@Database(name = TestDataBase.NAME, version = TestDataBase.VERSION)
public class TestDataBase {
  public static final String NAME = "MyDatabase";
  public static final int VERSION = 1;
}
```

to:
```
@Database(name = TestDataBase.NAME, version = TestDataBase.VERSION)
abstract class TestDataBase extends DBFlowDatabase {
  public static final String NAME = "MyDatabase";
  public static final int VERSION = 1;
}
```

**Comment by agrosner** [comment]
move the database name to the `FlowConfig`:
```
 FlowManager.init(FlowConfig.Builder(context)
                        .database(DatabaseConfig.builder(TestDatabase::class, AndroidSQLiteOpenHelper.createHelperCreator(context))
                        .databaseName("MyDatabase")
                                .build())
                        .build())
```
`name` in the `Database` annotation should have been removed. It will be removed in `5.0.0-alpha2`.

**Comment by lhy6962** [comment]
@agrosner Thanks for ur help, it build successful, but I found that the model.save() method has been changed at this version, there's one more parameter 'DatabaseWrapper'.How could I pass it ?Or how to use the version4.2.4 ?I tried to modify 
`def dbflow_version = "5.0.0-alpha1"` 
to  
`def dbflow_version = "4.2.4"`
but it always get error 
> Failed to resolve: com.github.agrosner.dbflow:lib:4.2.4

**Comment by lhy6962** [comment]
@agrosner Thanks!!

**Comment by agrosner** [comment]
annotation properties removed in `develop`, all set for next `5.0.0-alpha2`.

**Comment by qianmohunchen** [comment]
hi, move the database name to the FlowConfig: what mean? I get another error. please update readme text.
