### ISSUE TITLE
Upgrade dbflow version question

### ISSUE THREAD

**Issue by svran** [agrosner/DBFlow#1631]
DBFlow Version:5.0.0-alpha1

继承至BaseModel中的save(),为什么必须DatabaseWrapper参数,DatabaseWrapper从哪儿获取?
之前使用4.2.4版本中不需要;
Save() method in inherited to "BaseModel", why must fill in "DatabaseWrapper" parameter and "DatabaseWrapper" where to get it from?
Not needed before version 4.2.4;

**Comment by agrosner** [comment]
This is a question. I didn't do a full proper migration / release notes on why the change was made. 
```kotlin
database<AppDatabase>()
// or
FlowManager.getDatabase(AppDatabase::class.java)
```
To summarize the change from `model.save()` to `model.save(db)`:
1. This is to encourage you to switch to utilizing async database [transactions](https://dbflow.gitbook.io/dbflow/v/develop/usage2/usage/storingdata#transactions)  and not using the main thread. 
2. To prevent the error of utilizing the empty method (without a wrapper) in DB migrations, causing a recursive DB access exception.
3. Simplifies the API surface of DBFlow, not needing duplicate wrapper vs. non-wrapper methods everywhere.
4. Encourages dependency injection of the database instead, to make it easier for testing.

**Comment by agrosner** [comment]
To note, this affects pretty much any method, sqlite wrapper query, or anything else that utilizes DB access in it. There are a few Kotlin helpers to make the API not so terrible:
```kotlin
model.insert(database<AppDatabase>()) // not recommended
database<AppDatabase> { db -> // db closure
  val rows = db.executeTransaction(object: ITransaction<Long> {
    override fun execute(db: DatabaseWrapper) =  model.insert(db)
  }) // not recommended running on Main Thread, only execute in BG
  
  // recommended, runs on separate single-threaded DB queue.
  db.beginTransactionAsync { db -> model.insert(db)  }
    .execute { result ->
      // success
   }
  
  // recommended, runs on single threaded db queue, provides callbacks
  db.beginTransactionAsync { db -> model.insert(db)  }
  .execute(
   ready = { transaction -> } // perform any setup.
   error = { transaction, error -> // handle any exceptions here },
   completion = { transaction -> // called when transaction completes success or fail }
  ) { transaction, result ->
  // utilize the result returned
  }
}
```

**Comment by svran** [comment]
Ok,thank you very much!
