### ISSUE TITLE
SqlCipher documentation seems incorrect

### ISSUE THREAD

**Issue by davidmaulick002** [agrosner/DBFlow#1635]
DBFlow Version:
5.0.0-alpha1

Bug or Feature Request:
Issue with documentation at https://dbflow.gitbook.io/dbflow/usage2/advanced-usage/sqlciphersupport

Description:
I am trying to get sqlcipher working and was able to find the documentation located at https://dbflow.gitbook.io/dbflow/usage2/advanced-usage/sqlciphersupport. However, it appears that the provided db initialization code at the bottom is incomplete. It appears to be missing a closing bracket, and it seems to be missing some code.

**Comment by douglasalipio** [comment]
It should work:

```java
  fun initDatabase(userToken: String) {

        val dbConfig = FlowConfig.Builder(UmbrellaApplication.instance)
                .addDatabaseConfig(DatabaseConfig
                        .Builder(AppDatabase::class.java)
                        .databaseName(AppDatabase.NAME)
                        .openHelper { databaseDefinition, helperListener ->
                            SQLCipherHelperImpl(databaseDefinition, helperListener, userToken)
                        }.build())
                .build()
        FlowManager.init(dbConfig)
    }
```

**Comment by davidmaulick002** [comment]
It appears that this may be a solution for an older dbflow version. I believe 'addDatabaseConfig' should be 'database'. And It seems that 'openHelper' may be deprecated.

**Comment by douglasalipio** [comment]
> It appears that this may be a solution for an older dbflow version. I believe 'addDatabaseConfig' should be 'database'. And It seems that 'openHelper' may be deprecated.

Well, I didn't get the warner on 5.0.0-alpha1 and I tried the code of the documentation and it' doesn't work.

**Comment by agrosner** [comment]
Have you looked at: https://dbflow.gitbook.io/dbflow/v/develop/usage2/advanced-usage/sqlciphersupport ?
I guess since the lib is changing, I am working on updating the documentation to reflect the new changes. Thank you for reporting this. Once changes from `develop` get merged into master, the regular documentation will update to latest.

**Comment by davidmaulick002** [comment]
Thank you. It appears that the documentation on the develop guide also needs to be changed as it is the same as the master docs code.

**Comment by agrosner** [comment]
```
FlowManager.init(FlowConfig.Builder(this)
  .database(
      DatabaseConfig.Builder(CipherDatabase::class) { db, callback -> SQLCipherHelperImpl(databaseDefinition, callback))
      .build())
  .build())
```
related to #1637
