### ISSUE TITLE
Init database doesn't work after put the wrong password for the first time.

### ISSUE THREAD

**Issue by douglasalipio** [agrosner/DBFlow#1636]
DBFlow Version: 5.0.0-alpha1 and 4.2.4

Bug: release the database

Description:

So when I try to `FlowManager.init(dbConfig)` with the correct password after put for the first time the worng password it throws an exception `net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;` if I try to reopen, close or any sql operation `FlowManager.getConfig().closeDB`, `FlowManager.getDatabase().isDatabaseIntegrityOk` . According to this [thread](https://github.com/sqlcipher/android-database-sqlcipher/issues/76)

> SQLCipher for Android does not know that the password you have provided is invalid following a sqlite3_key call, as the database key isn't used until a SQL command is issued against the database following the sqlite3_key, such as the setLocale(...) method you reference above. The problem is, providing an invalid key may be only one of possible other scenarios that could be the problem at the point the first SQL statement is executed. A corrupt data file, a failed HMAC check, or opening a non database file could result in this same error message. For a detailed description of this please review this thread. It would be best to catch the exception when attempting to open the database and handle accordingly within the client application.

if I can't do any sql operator after init the database with the wrong password, what should I do to retrieve the access again?

**Comment by agrosner** [comment]
This seems like a SQLCipher question to me. How are you initing the DB with the wrong password, what is the scenario you're seeing? (So i get a better idea of why this is happening)

**Comment by douglasalipio** [comment]
Hey, @agrosner thanks for the answer. So basically, am doing a login feature where I have to sign the database access even the users need it.

Even the user put the password and clicks on the login button I have to try to open a connection with the database (I'm not sure if it's the best way to do because on the documentation it's said to put the initialization of the data into Application class).

View code
`view.loginButton.setOnClickListener { doLogin(userToken) }` 

Presenter code

 ```kotlin
fun doLogin(userToken: String) {
        val dbConfig = FlowConfig.Builder(UmbrellaApplication.instance)
                .addDatabaseConfig(DatabaseConfig
                        .Builder(AppDatabase::class.java)
                        .databaseName(AppDatabase.NAME)
                        .openHelper { databaseDefinition, helperListener ->
                            SQLCipherHelperImpl(databaseDefinition, helperListener, userToken)
                        }.build())
                .build()
        FlowManager.init(dbConfig)
}
```
```kotlin
fun isDatabaseOkay() {
        if (FlowManager.getDatabase(AppDatabase.NAME).isDatabaseIntegrityOk) {
            //access to the application
        } else {
            //deny access to the application
        }
}
```

As SQLCipher doesn't provide a way to test if the connection was successfully so I'm using this function to test if it works or not.  `FlowManager.getDatabase(NAME).isDatabaseIntegrityOk`.

First scenario:
1- Put the correct password
2- Result OK

Second scenario:
1 - Put the wrong password
2 - the function isDatabaseIntegrityOk throw a exception (not return false) 
3 - put the correct password after try once with an incorrect password the function isDatabaseIntegrityOk throw an exception.

I think that behavior throws an exception, if I FlowManager.init(dbConfig) passing a wrong password, is okay but after trying another time with the correct password it still throws an exception. So is not possible to call `FlowManager.init(dbConfig)` many times?

**Comment by douglasalipio** [comment]
So It was fixed.  What I did  was never try to initialize the database with an incorrect password 

```kotlin
private fun checkPassword(userToken: String): Boolean {
        SQLiteDatabase.loadLibs(application)
        return try {
            val db = SQLiteDatabase.openOrCreateDatabase(application
                    .getDatabasePath(AppDatabase.NAME + ".db").path, userToken, null)
            db.isOpen
        } catch (e: SQLiteException) {
            e.printStackTrace()
            false
        }
    }
```
Than if `checkPassword(userToken: String)` return true I try to init it.

```kotlin
fun doLogin(userToken: String) {
       val dbConfig = FlowConfig.Builder(context)
               .addDatabaseConfig(DatabaseConfig
                       .Builder(AppDatabase::class.java)
                       .databaseName(AppDatabase.NAME)
                       .openHelper { databaseDefinition, helperListener ->
                           SQLCipherHelperImpl(databaseDefinition, helperListener, userToken)
                       }.build())
               .build()
       FlowManager.init(dbConfig)
}
```
I still don't understand why I can't close the dbflow after pass an incorrect password :)
