### ISSUE TITLE
Help setting up existing database with SQLcipher in Kotlin

### ISSUE THREAD

**Issue by davidmaulick002** [agrosner/DBFlow#1637]
DBFlow Version:
5.0.0-alpha1

Bug or Feature Request:
I would just like some assistance and explanation for setting up dbflow with an existing database with sqlcipher, the 5.0.0-alpha1 version in Kotlin. 

Description:

As of now I am working on just reading in data from a table that matches this schema:
```kotlin
@Table(database = MyDBFlowDatabase::class)
class DbfAcivityModel(@PrimaryKey
                      @NotNull
                        var _ID: Int,
                      @Column
                      @NotNull
                        var activityName: String,
                      @Column
                        var activityCode: String,
                      @ColumnIgnore
                        var isActive: Int = -1) : BaseModel()
```
Any comments on this setup are welcomed. One question I do have about the above is what exactly is the reason of extending the BaseModel class?

Here is initialization logic that another recommended on issue 1635.
```kotlin
fun initDatabase(userToken: String) {
        val dbConfig = FlowConfig.Builder(context)
                .addDatabaseConfig(DatabaseConfig
                        .Builder(AppDatabase::class.java)
                        .databaseName(AppDatabase.NAME)
                        .openHelper { databaseDefinition, helperListener ->
                            SQLCipherHelperImpl(databaseDefinition, helperListener, userToken)
                        }.build())
                .build()
        FlowManager.init(dbConfig)
    }
```
For the above logic I believe 'addDatabaseConfig' should be 'database' and that 'openHelper' may be deprecated or changed. 

Finally I am trying to retrieve from the database:
val t1 = (select from DbfAcivityModel::class).list

I would like to be using the most up to date syntax and  techniques so any comments on the above code are welcomed!

**Comment by davidmaulick002** [comment]
Here is the sqlCipher helper I am using.
class SQLCipherHelper(context: Context,
                              databaseDefinition: DBFlowDatabase,
                              callback: DatabaseCallback?)
    : SQLCipherOpenHelper(context, databaseDefinition, callback) {
    override val cipherSecret get() = "dbflow-rules"
}

**Comment by agrosner** [comment]
@davidmaulick002 you no longer need to extend `BaseModel` unless you want inherited methods for `save()`, `insert()`, etc. operations where you can override them. Otherwise you can utilize the kotlin extension versions which dont require it. The other difference is each `BaseModel` will cache the `ModelAdapter` under the hood so if its saved or used multiple times you dont look it up all the time. 

change:
```
val t1 = (select from DbfAcivityModel::class).list

```

to :
```kotlin
database<MyDatabase> {  db ->
  val t1 = (select from DbfAcivityModel::class).queryList(db)
} 
```

as for:
```kotlin
fun initDatabase(userToken: String) {
        val dbConfig = FlowConfig.Builder(context)
                .addDatabaseConfig(DatabaseConfig
                        .Builder(AppDatabase::class.java)
                        .databaseName(AppDatabase.NAME)
                        .openHelper { databaseDefinition, helperListener ->
                            SQLCipherHelperImpl(databaseDefinition, helperListener, userToken)
                        }.build())
                .build()
        FlowManager.init(dbConfig)
    }
```

OpenHelper is now in the constructor of the builder. It looks like this is a mistake by removing it, for now you can add:
```kotlin
fun initDatabase(userToken: String) {
        val dbConfig = FlowConfig.Builder(context)
                .addDatabaseConfig(DatabaseConfig
                        .Builder(AppDatabase::class.java) { databaseDefinition, helperListener ->
                            SQLCipherHelperImpl(databaseDefinition, helperListener, userToken)
                        }
                        .databaseName(AppDatabase.NAME)
                        .openHelper.build())
                .build()
        FlowManager.init(dbConfig)
    }
```

**Comment by davidmaulick002** [comment]
Thank you for the help.
It appears the initialization logic is still not exactly correct for this version.

Again, for reference here is my 'SQLCipherHelperImpl' class:
`class SQLCipherHelperImpl(context: Context,
                              databaseDefinition: AppDatabase,
                              callback: DatabaseCallback?)
    : SQLCipherOpenHelper(context, databaseDefinition, callback) {
    override val cipherSecret get() = "dbflow-rules"
}`

Here are my observations:
1) 'addDatabaseConfig' should be 'database'
2) The arguments for 'SQLCipherHelperImpl' need to be changed in some way as the 'SQLCipherHelperImpl' implementation docs direct us to implement it as shown above... Therefore there is no usertoken parameter in its constructor, likewise the first argument should be the context.

**Comment by davidmaulick002** [comment]
Following up on this.
Thank you.

**Comment by agrosner** [comment]
Thank you for the reminder, I will get to this and update the docs.

**Comment by agrosner** [comment]
it should be this:
```
fun initDatabase(userToken: String) {
        val dbConfig = FlowConfig.builder(context)
                .database(DatabaseConfig.builder(AppDatabase::class) { db, callback ->
                            SQLCipherHelperImpl(context, db, callback)
                        }
                        .databaseName(AppDatabase.NAME)
                        .build())
                .build()
        FlowManager.init(dbConfig)
    }
```

**Comment by agrosner** [comment]
https://dbflow.gitbook.io/dbflow/v/develop/usage2/advanced-usage/sqlciphersupport
