### ISSUE TITLE
Problems with TableView creation in Kotlin

### ISSUE THREAD

**Issue by martin-felczerek** [agrosner/DBFlow#1638]
DBFlow Version:
5.0.0-alpha1
Bug or Feature Request:
Bug
Description:
The approach (as described in docu) for TableViews is to create a class annotated with `@TableView` attribute and add one static field of `Query` type annotated with `@ModelViewQuery`. The problem is, in current alpha `ModelViewQuery` has `Target` attribute set to FUNCTION or PROPERTY_GETTER which makes it impossible to annotate a JVM_STATIC field (as it was done in the past). So, I switched it to simple companion object property and annotated it with `@get:ModelViewQuery`. As it's a getter, it works, but now compiler says:

error: *==========* :(class name) is missing the @ModelViewQuery field.*==========*

**Comment by martin-felczerek** [comment]
OK, I probably found a solution, but it needs more doc.
the field needs `@get:` type annotation for ModelViewQuery, and it needs to be marked with `@JvmStatic` now (not `@JvmField`). The problem is, we still need "JVM" annotation and it's uglier than before, so maybe it should be changed in future version

**Comment by agrosner** [comment]
thank you for catching the bug in the documentation. I will fix it.

**Comment by agrosner** [comment]
it should look something like:
```kotlin
companion object {
        @JvmStatic
        @ModelViewQuery
        fun getQuery(): From<Author> = select((first_name + last_name).`as`("name")) from Author::class
    }
```
I added ability to use as property w/ `AnnotationTarget.PROPERTY`:
```kotlin
companion object {
        @JvmStatic
        @ModelViewQuery
        val query: From<Author> = select((first_name + last_name).`as`("name")) from Author::class
    }
```

Or as a getter:
```kotlin
companion object {
        @JvmStatic
        @ModelViewQuery
        val query: From<Author> get() = select((first_name + last_name).`as`("name")) from Author::class
    }
```
In `5.0.0-alpha2`

**Comment by agrosner** [comment]
in `develop`: https://dbflow.gitbook.io/dbflow/v/develop/usage2/usage/modelviews
