### ISSUE TITLE
how to use ContentUtils.queryList? 

### ISSUE THREAD

**Issue by 12ndxu** [agrosner/DBFlow#1641]

**Comment by 12ndxu** [comment]
it need to much param，I need query all data from another app

**Comment by agrosner** [comment]
ill admit its not the prettiest API or useful in the library.

```kotlin
queryList(contentResolver: ContentResolver, queryUri: Uri,
                                     table: Class<TableClass>,
                                     databaseWrapper: DatabaseWrapper,
                                     whereConditions: OperatorGroup,
                                     orderBy: String, vararg columns: String)
```
`contentResolver` comes from your current `Context`.
`queryUri` is the content provider uri that you pass to query
`databaseWrapper` is the `FlowManager.getDatabase` or `database<AppDatabase>()` object
`whereConditions`is an `OperatorGroup` which is just combining operators such as `Column.eq(value)`
`orderBy` is the `OrderBy.ASCENDING` or descending
`columns` are the projected columns in the query. If empty, its all.
