### ISSUE TITLE
Cursor window allocation of 2048 kb failed

### ISSUE THREAD

**Issue by zhy060307** [agrosner/DBFlow#1642]
# android.database.CursorWindowAllocationException

DBFlow Version:4.0.4

Bug or Feature Request:

Description: "onError: android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=288 (# cursors opened by this proc=288)android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=288 (# cursors opened by this proc=288)->	at android.database.CursorWindow.<init>(CursorWindow.java:108)->	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)->	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)->	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)->	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)->	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:237)->	at android.database.CursorWrapper.moveToFirst(CursorWrapper.java:65)->	at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:21)->	at com.raizlabs.android.dbflow.sql.queriable.SingleModelLoader.convertToData(SingleModelLoader.java:32)->	at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:72)->	at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:60)->	at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:53)->	at com.raizlabs.android.dbflow.sql.queriable.ModelLoader.load(ModelLoader.java:36)->	at com.raizlabs.android.dbflow.sql.language.BaseModelQueriable.querySingle(BaseModelQueriable.java:69)->	at com.raizlabs.android.dbflow.sql.language.BaseTransformable.querySingle(BaseTransformable.java:126)->	at wg.roomis.data.config.repository.SpaceInfoRepositoryImpl.find(SpaceInfoRepositoryImpl.java:35)->	at wg.roomis.data.config.repository.SpaceInfoRepositoryImpl.get(SpaceInfoRepositoryImpl.java:31)

```
private SpaceBindInfoEntity find() {
        return SQLite.select().from(SpaceBindInfoEntity.class).querySingle();
    }
```

**Comment by bingxueai123456** [comment]
你最后是怎么解决这个问题的？求大声教我

**Comment by agrosner** [comment]
related to #1700
