### ISSUE TITLE
Java docking problem

### ISSUE THREAD

**Issue by qaz5506811123** [agrosner/DBFlow#1644]
# ISSUE\_TEMPLATE

DBFlow Version:5.0.0

Bug or Feature Request:

Description:I am currently using java, the document says that the database of the project does not need to inherit, but after I make the project, I will report that I want to inherit the dbflowdatabase, and initialize it in the application. The document has FlowConfig.builder().addDatabaseConfig() method. But there is actually no, do you want to update the docking document?

**Comment by agrosner** [comment]
check out updated docs here https://app.gitbook.com/@dbflow/s/dbflow/v/develop/usage2/usage/databases
Not sure the question here
