### ISSUE TITLE
[Question] Get relationship info of a table

### ISSUE THREAD

**Issue by 3dmg** [agrosner/DBFlow#1646]
DBFlow Version: 4.2.4

Question:

Hi, we use the ForeignKey annotation to create the relationship between tables, like this:

```
@Table(database = MeisterTaskDb::class)
class Group : BaseModel() {

    @Column
    @ForeignKey(tableClass = Team::class, onUpdate = ForeignKeyAction.CASCADE, onDelete = ForeignKeyAction.CASCADE)
    @SerializedName("team_id")
    @Expose
    var teamId: Long? = null
    ...
```

Is it possible to get this info later in code? 
The info would be: Has the table `Group` a relationship with another table -> when yes, with which table and which id?

Thanks in advance!

**Comment by agrosner** [comment]
not currently with the library. You can with SQLite look at table info: https://www.sqlitetutorial.net/sqlite-tutorial/sqlite-describe-table/
