### ISSUE TITLE
Support Gradle incremental annotation processing

### ISSUE THREAD

**Issue by WonderCsabo** [agrosner/DBFlow#1648]
It would be nice to support incremental compilation, if possible.

https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by mseroczynski** [comment]
Any updates on that? DBFlow is the only library around that still has this blocker. @agrosner

**Comment by agrosner** [comment]
fixed in develop for 5.0.0-alpha2
