### ISSUE TITLE
kapt issues

### ISSUE THREAD

**Issue by matteinn** [agrosner/DBFlow#1653]
# ISSUE\_TEMPLATE

DBFlow Version: 
4.2.4

Bug or Feature Request:
Build error

Description:
I'm getting the following error when syncing the project using the latest Kotlin version as of today: 1.3.21. Works fine on 1.3.11.
`Could not find method kapt() for arguments [com.github.raizlabs.dbflow:dbflow-processor:4.2.4]`
Is there any way to fix this?

build.gradle relevant content:
```
ext.dbflow_version = '4.2.4'
kapt "com.github.raizlabs.dbflow:dbflow-processor:${dbflow_version}"
implementation "com.github.raizlabs.dbflow:dbflow-core:${dbflow_version}"
implementation "com.github.raizlabs.dbflow:dbflow:${dbflow_version}"
implementation "com.github.raizlabs.dbflow:dbflow-kotlinextensions:${dbflow_version}"
```

**Comment by David-W-Simons** [comment]
@matteinn Great callout - This issue seems to still occur  with Kotlin 1.3.50. downgrading to:
`ext.kotlin_version = '1.3.11'`
solved the issue.
