### ISSUE TITLE
BaseProviderModel#load can lead to  cursor  not close

### ISSUE THREAD

**Issue by Zhangshua** [agrosner/DBFlow#1655]
# ISSUE\_TEMPLATE

DBFlow Version: 4.2.4  5.0.0-alpha1

Bug or Feature Request:

Description:
override fun <T> load(whereOperatorGroup: OperatorGroup,
       ..
            if (flowCursor.moveToFirst()) {
                val model: T = modelAdapter.loadFromCursor(flowCursor, wrapper) as T
                flowCursor.close()
                return model
            }
       ...
    }

when cursor is empty, flowCursor.moveToFirst() return false, then flowCursor will not close

**Comment by agrosner** [comment]
oh good catch.

**Comment by agrosner** [comment]
in `develop`
