### ISSUE TITLE
What is it DatabaseWrapper?

### ISSUE THREAD

**Issue by VeiNPrk** [agrosner/DBFlow#1661]
# ISSUE\_TEMPLATE

DBFlow Version: 5.0.0-alpha1

Bug or Feature Request:
save(DatabaseWrapper) in BaseModel cannot be applied
Description:
Why in the latest version I can not just save the object extended from BaseModel? In the documentation about this does not say anything.

**Comment by sangxb** [comment]
Did you solve it?

**Comment by antdeveloper** [comment]
the same problem :/

**Comment by LeeYKKK** [comment]
Did you solve it?impendency

**Comment by fakefacebook** [comment]
@agrosner Please Help us in this Question. What I passed in Save() method?

**Comment by aiguanglin** [comment]
the same problem too!

**Comment by Nhitro** [comment]
Hi everyone !

You have to pass your database which now delegates to the DatabaseWrapper

`myModel.save(FlowManager.getDatabase(MyDatabase.class));`

**Comment by agrosner** [comment]
Its the database wrapper that provides abstracted functionality that a normal `SQLiteDatabase` object would provide. So we can swap implementation for other kinds like SQLCipher. You need to be explicit in passing the db in methods from now on as the previous implementation had a few drawbacks:
1. Every method in the library was then expected to supply a counterpart that took 1 or no database, increasing method count.
2. By running migrations with wrapper queries you would easily run into stackoverflow issues by leaving out the `DatabaseWrapper` parameter.
3. Encourages not using transactions by calling `.save()` synchronously
4. Requires implict db lookup by model on every call, which impacts performance.

**Comment by agrosner** [comment]
new usage docs for 5.0.0-alpha2 https://dbflow.gitbook.io/dbflow/v/develop/usage2/usage/databases
hopefully are more clear
