### ISSUE TITLE
Will running multiple DBFlow databases at the same time cause any problems?

### ISSUE THREAD

**Issue by davidmaulick002** [agrosner/DBFlow#1663]
# Running Multiple Databases with DBflow

DBFlow Version:
5.0.0-alpha1

Description:
Because of certain requirements on my current project I need to run two, possibly three different sqLite databases at the same time on my Android app. Can DbFlow support this; are there any issues that I should look out for?
Also possibly worth noting, all of the databases will be sqlCipher Databases.

**Comment by agrosner** [comment]
yep shouldnt be any issues. we support multiple databases and each have their own set of transaction queues and isolated objects. One gotcha is models can only live within one db and TypeConverters are global.
