### ISSUE TITLE
How does DbFlow (or Android Studio) generate the database files on device file system for SqlCipher Databases?

### ISSUE THREAD

**Issue by davidmaulick002** [agrosner/DBFlow#1664]
# How DbFlow (or Android Studio) generates database files for SqlCipher Databases

DBFlow Version:
5.0.0-alpha1

Description:
I currently have two DbFlow databases associated with my Android application - one is sqlCipher and the other is not. They both seem to be running correctly... 

However my actual question results from inspecting the on device file system. I notice that both the the sqlCipher and non-SqlCipher db there are three files; 1) .db 2) .db-shm 3) .db-wal.

I am curious:
 1) what is the purpose of these three different files per database and 
 2) My SqlCipher database .db file compressed from 53KB to 4 KB while my unencrypted one stayed the same size - why is this? 

I realize this may not be dbflow specific, however I felt this may be a useful question for those that are curious.

**Comment by agrosner** [comment]
this is not related to DBFlow. please consult with the SQLCipher team or stackoverflow :)
