### ISSUE TITLE
How to create temp table with DbFlow?

### ISSUE THREAD

**Issue by anton8900** [agrosner/DBFlow#1666]
Do you support temp tables? If yes please explain me how to create and use temp table using DbFlow

**Comment by agrosner** [comment]
not yet, but will add it

**Comment by agrosner** [comment]
in `develop`. use:
`@Table(..., temporary = true,  createWithDatabase = false)`

disabling `createWithDatabase` can ensure on db startup it doesn't get created (if you wish to manually create and drop it)

then to activate it:
```kotlin
  database<MyDatabase> { db ->
            modelAdapter<MyTempModel>().createIfNotExists(db)

            // can drop it later if so wish
            modelAdapter<TempModel>().drop(db)
}
```
