### ISSUE TITLE
Convert List 

### ISSUE THREAD

**Issue by Gelassen** [agrosner/DBFlow#1668]
# ISSUE\_TEMPLATE

DBFlow Version:
4.2.4

Bug or Feature Request:
I want to save this into the db

```
`@Table(database = AppDatabase.class,
        name = "Contacts",
        allFields = true)
public class ContactsModel
        extends BaseModel
{
    @PrimaryKey
    public String contactId;
    public String firstName;
    public String lastName;
    public String imagePath;
    @Column(typeConverter = ContactTypeConverter.class)
    public List<String> phones;

    public ContactsModel()
    {
        /* required by dbflow */
    }
```

    public ContactsModel(String contactId, String firstName, String lastName,
                         String imagePath, List<String> contacts)
    {
        this.contactId = contactId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.imagePath = imagePath;
        this.phones = contacts;
    }
}`

Description:
I have a type converter which I want to use to convert list of string to database

```
`@com.raizlabs.android.dbflow.annotation.TypeConverter
public class ContactTypeConverter
        extends TypeConverter<String, List>
{
    @Override
    public String getDBValue(List model)
    {
        return new Gson().toJson(model);
    }
```

    @Override
    public List getModelValue(String json)
    {
        Type collectionType = new TypeToken<Collection<String>>(){}.getType();
        return new Gson().fromJson(json, collectionType);
    }
}`

According to this five years old issue it should work: 
https://github.com/agrosner/DBFlow/issues/5#issuecomment-63842077
 
but compiler gives me this error:
`error: *==========* :The specified custom TypeConverter's Model Value java.util.List from com.tsrpay.android.data.ContactTypeConverter must match the type of the column java.util.List<java.lang.String>.*==========*`

Would you mind to take a look what is not right here?

**Comment by agrosner** [comment]
did you try removing the type parameter on the field? via here: https://dbflow.gitbook.io/dbflow/v/develop/usage2/usage/models#columns
```
List<T> : List columns are not supported and not generally proper for a relational database. However, you can get away with a non-generic List column via a TypeConverter. But again, avoid this if you can.
```
