### ISSUE TITLE
Right way to enforce Not Null on FK column using model

### ISSUE THREAD

**Issue by luizfp** [agrosner/DBFlow#1669]
# ISSUE\_TEMPLATE

DBFlow Version: 4.2.4

Bug or Feature Request: Bug/Question

Description:
I have a simple parent and child table. The child table has a FK to parent and I need that column to be NOT NULL. 

Here is the code:

``` java
@Table(database = DB.class, name = "FkNotNullParent")
public class FkNotNullParent extends BaseModel {
    @NotNull
    @Column
    @PrimaryKey
    Long id;

    public FkNotNullParent() {
    }
}
```

``` java
@Table(database = DB.class, name = "FkNotNullChild")
public class FkNotNullChild extends BaseModel {
    @NotNull
    @PrimaryKey(autoincrement = true)
    @Column(name = "_id")
    Long _id;

    @NotNull
    @Column
    @ForeignKey(saveForeignKeyModel = false)
    FkNotNullParent parent;

    public FkNotNullChild() {
    }
}
```

Looking at the generated `FkNotNullChild_Table` the create table code does not contains a NOT NULL constraint for the FK column:

``` java
@Override
  public final String getCreationQuery() {
    return "CREATE TABLE IF NOT EXISTS `FkNotNullChild`(`_id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ON CONFLICT FAIL, `parent_id` INTEGER"+ ", FOREIGN KEY(`parent_id`) REFERENCES " + com.raizlabs.android.dbflow.config.FlowManager.getTableName(sample.FkNotNullParent.class) + "(`id`) ON UPDATE NO ACTION ON DELETE NO ACTION" + ");";
  }
```

This means that the `@NotNull` does not work in that case.

Only using that way this seems to work:

``` java
@Table(database = DB.class, name = "FkNotNullChild")
public class FkNotNullChild {
    @NotNull
    @PrimaryKey(autoincrement = true)
    @Column(name = "_id")
    Long _id;

    @Column
    @ForeignKey(
            references = @ForeignKeyReference(
                    columnName = "parent",
                    foreignKeyColumnName = "id",
                    notNull = @NotNull))
    FkNotNullParent parent;

    public FkNotNullChild() {
    }
}
```
I assume that what makes this works is the parameter `notNull = @NotNull` inside the `@ForeignKeyReference` annotation. Using it generates a create table that contains the NOT NULL constraint.

Question: is that the expected behavior? 

I use DBFlow in other parts of my project and until today I had no idea that the `@NotNull` does not work for FK columns. This could be dangerous! I haven't find anything in the docs about that either.

**Comment by agrosner** [comment]
The expected behavior is to mark all of the foreign keys not null then? I think this was not full considered. Like if you make it `NotNull` but you only want one foreign key reference not null? currently there isn't a way to change it. I think what could happen is a processor error telling you to add it to the foreign key reference.

**Comment by agrosner** [comment]
Actually thinking a bit about it more, it will mark all foreign key as `NotNull` unless you explicitly set each reference individually.

**Comment by agrosner** [comment]
Now you can only specify it top-level as `@NotNull` or as part of a `ForeignKeyReference`. Using both will throw an error.
