### ISSUE TITLE
I cannot migrate in version 5.0.0 alpha 1

### ISSUE THREAD

**Issue by aikorn** [agrosner/DBFlow#1671]
# ISSUE\_TEMPLATE

DBFlow Version:5.0.0-alpha1

Bug or Feature Request:
@Database(version = 26, insertConflict = ConflictAction.IGNORE, updateConflict= ConflictAction.REPLACE)
public abstract class db_rep_en extends DBFlowDatabase {

    @Migration(version = 26, database = db_rep_en.class)
    public class Migration2 extends AlterTableMigration<cases_symp> {

        public Migration2(Class<cases_symp> table) {
            super(table);
        }

        @Override
        public void onPreMigrate() {
            addColumn(SQLiteType.TEXT, "myColumn");
            addColumn(SQLiteType.REAL, "anotherColumn");
        }
    }
}

Description:
extends  AlterTableMigration<cases_symp> - Cannot inherit from final 'com.dbflow5.migration.AlterTableMigration'

**Comment by himanshu-soni** [comment]
Facing same issue

**Comment by PKMNTR** [comment]
Same here, hope this can be solved

**Comment by aikorn** [comment]
Unfortunality.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Без
вирусов. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

вт, 14 мая 2019 г. в 21:38, Ricardo Ramirez <notifications@github.com>:

**Comment by zhonghaojie** [comment]
same issue

**Comment by 810872925** [comment]
How to solove it?

**Comment by 810872925** [comment]
Lower version？

**Comment by suryaadiputra** [comment]
same issue

**Comment by mseroczynski** [comment]
@agrosner Have you thought about releasing 5.0 any time soon or Room is the direction you would recommend migrating to?

**Comment by PKMNTR** [comment]
I check in pull requests and i'm almost sure that this request is the solution to this issue https://github.com/agrosner/DBFlow/pull/1667 but you also can use room or a lower version.

**Comment by 123vipulj** [comment]
`@Database(version = AppDatabase.VERSION)
public abstract class AppDatabase extends DBFlowDatabase {
    public static final int VERSION = 2;

    @Migration(version = 2, database = AppDatabase.class)
    public static class Migration1 extends BaseMigration{

        @Override
        public void migrate(@NotNull DatabaseWrapper databaseWrapper) {
          //FlowManager.getDatabase(AppDatabase.class).getModelClasses().get(0)  first index model class object
            ModelAdapter modelAdapter = FlowManager.getModelAdapter(FlowManager.getDatabase(AppDatabase.class).getModelClasses().get(0));
            databaseWrapper.execSQL("ALTER TABLE NewsContent ADD visit_count varchar(255)");
            databaseWrapper.execSQL(modelAdapter.getCreationQuery()); // recreate database model class again
        }
    }
}`

**Comment by agrosner** [comment]
this is fixed in 5.0.0-alpha2 (in develop) and plan to release it in the next week or so ( trying to get more fixes in )
