### ISSUE TITLE
EnForce Storage Location

### ISSUE THREAD

**Issue by hashweather** [agrosner/DBFlow#1672]
Hi, is there a way to enforce the location to store the database?.

Assuming I have a 1TB external micro sd card in the Android Device and I want the database and tables to be in  the 1TB external sd card, how do I enforce this? 

Thanks alot.

**Comment by agrosner** [comment]
You can do something like this:
https://medium.com/@mostasim/read-external-database-with-sqliteopenhelper-on-android-e87d66891f4e
You need to provide a context wrapper.

Then when initializing DBFlow, the specific database config should be specified:

```kotlin
FlowManager.init(appContext) {
  database<AppDatabase> (openHelperCreator =  AndroidSQLiteOpenHelper.createHelperCreator(wrappedContext))
}
```

(using 5.0.0-alpha2 syntax). For old syntax its just specifying a different `Context` for the `AndroidSQLiteOpenHelper` classs.
