### ISSUE TITLE
DB migrations failing after 4.1.0

### ISSUE THREAD

**Issue by JonatanPlesko** [agrosner/DBFlow#1673]
DBFlow Version: 4.2.4

Bug or Feature Request: Bug

Description:
This issue appears after 4.0.5 (and still persists in the latest stable version). It happens when there is an attempt to upgrade from database version 4, to version 7 (current) and the crash message is this:

> Caused by android.database.sqlite.SQLiteException: no such column: personTypeId (code 1): , while compiling: UPDATE `Person` SET `personTypeId`=`personId`
> #################################################################
> Error Code : 1 (SQLITE_ERROR)
> Caused By : SQL(query) error or missing database.
> 	(no such column: personTypeId (code 1): , while compiling: UPDATE `Person` SET `personTypeId`=`personId`)

The migration code looks like this:

```
@Database(name = MyDatabase.NAME, version = MyDatabase.VERSION)
public class MyDatabase {

    public static final String NAME = "MyDb";

    public static final int VERSION = 7;

    private MyDatabase() {

    }

    @Migration(version = 7, database = MyDatabase.class)
    public static class Migration7 extends AlterTableMigration<Person> {

        public Migration7(Class<Person> table) {
            super(table);
        }

        @Override
        public void onPreMigrate() {
            addColumn(SQLiteType.TEXT, "gender");
        }
    }

    @Migration(version = 5, priority = 2, database = MyDatabase.class)
    public static class Migration50 extends AlterTableMigration<Person> {

        public Migration50(Class<Person> table) {
            super(table);
        }

        @Override
        public void onPreMigrate() {
            addColumn(SQLiteType.INTEGER, "personTypeId");
        }
    }

    @Migration(version = 5, priority = 1, database = MyDatabase.class)
    public static class Migration51 extends BaseMigration {

        @Override
        public void migrate(@NonNull DatabaseWrapper database) {
            SQLite.update(Person.class)
                .set(Person_Table.personTypeId.eq(Person_Table.personId))
                .execute(database);
        }
    }
}
```

Migration was successful when using version 4.0.5 or lower, but failed (with the error above) when using version 4.1.0 or above.

**Comment by agrosner** [comment]
looks like the priority got flipped so that the lower the number, the higher the priority. Since it has touched a few versions in the middle, it will be left as is. I will update documentation so its clear.
