### ISSUE TITLE
Unable to use existing Database when also using sqlCipher

### ISSUE THREAD

**Issue by davidmaulick002** [agrosner/DBFlow#1674]
DBFlow Version:
5.0.0-alpha1

Bug or Feature Request:
Unable to use existing Database when also using sqlCipher, but can use existing database with plain sqlLite database

Description:
I have been successfully using Dbflow for a while now. In my application I use one sqlCipher database that is loaded with no existing values in its table. My second database is a plain database table that is loaded with existing rows in a couple of its tables. With this plain sqlLite database I am immediately able to identify that those entries are in the tables they're supposed to be in by looking at the size of the database in the device file explorer as well as querying out the values in code.

My issue is that I needed to move those existing tables from the plain sqlLite database to the sqlCipher database. This is where it stops working. Now after loading up the databases there is no sign of those entries. It is as if the sqlCipher database(and tables) is being created from scratch based on the ORM's and not actually using the provided existing sqlCipher database.

Here is how I am setting up the functioning plain sqlLite Database, and the broken sqlCipher database:

Configuration for plain SqlLite Database that is working:
- The name of the existing database file is 'normalDb.db' and is located in the asset folder

- Init Code:
```
val normalDbConfig = FlowConfig.Builder(this)
                .database(
                        DatabaseConfig.builder(normalDb::class, AndroidSQLiteOpenHelper.createHelperCreator(this))
                                .databaseName("normalDb")
                                .build())
                .openDatabasesOnInit(true)
                .build()

        FlowManager.init(normalDbConfig)
```
- Database declaration
```
@Database(version = normalDb.VERSION)
abstract class normalDb : DBFlowDatabase(){
    companion object {
        const val VERSION = 1
    }
}
```

Configuration for SqlCipher Database:
- The name of the existing database file is 'encryptedDb.db' and is located in the asset folder

- Init Code:
```
val encryptedDbConfig = FlowConfig.Builder(this)
                .database(
                        DatabaseConfig.Builder(encryptedDb::class) { db, callback -> SQLCipherHelper(this, db, callback) }
                                .databaseName("encryptedDb")
                            .build())
                .build()

        FlowManager.init(encryptedDbConfig)
```

- Database declaration
```
@Database(version = encryptedDb.VERSION)
abstract class encryptedDb : DBFlowDatabase(){
    companion object {
        const val VERSION = 1
    }
}
```

- SqlCipher helper:
```
class SQLCipherHelper(context: Context,
                              databaseDefinition: DBFlowDatabase,
                              callback: DatabaseCallback?)
    : SQLCipherOpenHelper(context, databaseDefinition, callback) {
    override val cipherSecret get() = "myPassword"
}
```

Any help is welcomed!!!

One more question, once I get the sqlCipher database working is there a way to change the passcode for it?

**Comment by pr0t3us** [comment]
I've also faced this issue. Seems like Dbflow can't find encrypted database in assets folder. I've managed to copy the db to app folder in the loading phase and then the library is picking it up.

**Comment by davidmaulick002** [comment]
@pr0t3us thanks for the input, I will try that out too.

However I was actually able to find a work around for my issue. It turns out the issue is that Dbflow can only load one existing database. In my original set up I was loading my normal sqlite database first, and then my sqlcipher db. As a result, the values from the first sqlite tables would load but not the second which happened to be sqlcipher.

Now that I changed the order and am loading the sqlcipher db first, the values get loaded in. Downside is now the sqlite values don't get loaded in (luckily this is okay for my use case).

Also. Dbflow does not support sqlcipher 4 as far as I can tell. Hopefully this changes soon.

**Comment by agrosner** [comment]
1. We don't support migration from one DB type to another. You can achieve it (not that easily) by streaming the rows from the table into a `FlowCursor` that you convert into the new db's model type to save. Since model classes cannot exist in multiple dbs (yet).
2. Password change is on the sqlcipher side. https://stackoverflow.com/a/26292817 though the password change you would have to:
- first open DB with the old value
- run those SQL commands on old db
- reopen
```kotlin
database<CipherDatabase> { db ->
  db.execSQL("PRAGMA key = 'old_password';")
  db.execSQL("PRAGMA rekey = 'new_password';")
  db.reopen()
}
```
