### ISSUE TITLE
Unknown constant tag 119 in class file  DatabaseValidator

### ISSUE THREAD

**Issue by abdymm** [agrosner/DBFlow#1678]
# ISSUE\_TEMPLATE

DBFlow Version: 4.2.4

Bug or Feature Request:
Unknown constant tag 119 in class file com/raizlabs/android/dbflow/processor/DatabaseValidator

Description:
when i resync to gradle today and run to my device i got this error, i just re sync and i got that error
```
Unknown constant tag 119 in class file com/raizlabs/android/dbflow/processor/DatabaseValidator
```
what i supposed to do @agrosner 
thanks

**Comment by agrosner** [comment]
not quite sure what to do, seems like a java issue. Did you ever find out what caused it?
