### ISSUE TITLE
how to update dbflow databse when i add some data only in table, not rename or add colume Ask Question

### ISSUE THREAD

**Issue by alijohar** [agrosner/DBFlow#1680]
# ISSUE\_TEMPLATE

DBFlow Version: 4.24

Bug or Feature Request:

Description:
I am using DBFLOW library, I have prepacked database. now I want to add new data to my database in two tables when I increase the version database and update my app, the old version of the database is still showing.

**Comment by agrosner** [comment]
Create a custom migration class, increment DB version and to the data migration. DBFlow runs all db migrations on create of DB and each subsequent diff. I believe from a prepackaged DB, you need to ensure its schema matches your current as migrations will not run.

**Comment by agrosner** [comment]
prepackaged is generally meant as a "quick-start" of the app, so you should ensure the prepackaged comes with the new data in the database, or when opening db, you schedule a transaction task to insert the data.
