### ISSUE TITLE
DBFlow Transaction  does not  support  operation of roll back   

### ISSUE THREAD

**Issue by ryan3216** [agrosner/DBFlow#1681]
DBFlow Transaction does not support operation of roll back
DBFlow Version:
All
Bug or Feature Request:
There is no Operation of roll back support.
Description:
Roll back is part of the Transaction operation,  But DBFlow doesn`t support it.

**Comment by agrosner** [comment]
rollback is not supported other than if you throw an exception within the Transaction itself. that will not set the transaction as successful.
