### ISSUE TITLE
ERROR: Failed to resolve: com.github.Raizlabs.DBFlow:dbflow:5.0.0-alpha1

### ISSUE THREAD

**Issue by emiraslan** [agrosner/DBFlow#1682]
# It Does Not Resolve

DBFlow Version: 5.0.0-alpha1

Bug: Failed to resolve com.github.Raizlabs.DBFlow dependencies

Description:
![werwerw](https://user-images.githubusercontent.com/18244093/59524268-72ba2400-8ee4-11e9-9004-1c053a321d60.PNG)

No other solution mentioned in previous issues helped. Should I downgrade to an older version? Why does the latest version not work?

**Comment by emiraslan** [comment]
When I downgraded it to version 4.2.4, it worked.

**Comment by amoikevin** [comment]
try this:
maven { url 'https://jitpack.io' }

 implementation 'com.github.agrosner.dbflow:core:5.0.0-alpha1'
 implementation 'com.github.agrosner.dbflow:lib:5.0.0-alpha1'
