### ISSUE TITLE
Property COUNT now work in version 5.0.0-alpha1 kotlin

### ISSUE THREAD

**Issue by Afra55** [agrosner/DBFlow#1684]
# 5.0.0-alpha1

DBFlow Version:5.0.0-alpha1

Bug or Feature Request:
Like this, i can not use `.count(database)`

Description:
![image](https://user-images.githubusercontent.com/7507927/60584483-fa969e00-9dbf-11e9-9537-0b05a1cbe3d4.png)

**Comment by Nailik** [comment]
`count` is deprecated anyway you should use `longValue`
