### ISSUE TITLE
 Extending library's BaseData can't generate table

### ISSUE THREAD

**Issue by wangsuicheng** [agrosner/DBFlow#1685]
DBFlow Version: 4.2.2

Description: 
In the sdk-library, I have a BaseData extends BaseModel, and in app dir, I write a Metadata extends BaseData, and starting build app ,it failed, can't genereate table by extending library's BaseData class ?

**Comment by agrosner** [comment]
You cannot extend other module classes without using `@InheritedColumn` most likely https://dbflow.gitbook.io/dbflow/v/develop/usage2/usage/models#inherited-columns

This is because each module is its own compilation unit and annotation processors do not traverse all at once.
