### ISSUE TITLE
How to get specific item inside for loop from table as String

### ISSUE THREAD

**Issue by msslgomez** [agrosner/DBFlow#1686]
# ISSUE\_TEMPLATE

DBFlow Version:

Bug or Feature Request:

Description:
I want to compare the start date and end date to add them to different arrays, i need to format the string to a date and then back again save them to a list<string>. I don't know how to get the init_date info from the table, format it and then save it to another array.

```
List<Events> eventlistI = SQLite.select(Events_Table.init_date).from(Events.class).queryList();
//        List<Events> eventlistE = SQLite.select(Events_Table.end_date).from(Events.class).queryList();

        int size = eventlistI.size();
        System.out.println(eventlistI.size());

        for (int i = 0; i < size; i++) {

            System.out.println(i);

            String s = String.valueOf(SQLite.select(Events_Table.init_date).from(Events.class).where(Events_Table.id.eq(i -1)));
```

**Comment by agrosner** [comment]
you can use `SQLite.select(Events_Table.init_date).from(Events.class).where(Events_Table.id.eq(i -1)).stringValue(db)` as of 5.0.0-alpha2 `develop`. Otherwise on older versions:
```kotlin
val query = (select(Events_Table.init_date) from Events::class where Events_Table.id.eq(i -1))
.compileStatement(query).use { statement -> statement.simpleQueryForString() }
```
