### ISSUE TITLE
database locked

### ISSUE THREAD

**Issue by mayinchu** [agrosner/DBFlow#1688]
# ISSUE\_TEMPLATE

DBFlow Version:4.0.0-beta5

Bug or Feature Request:
 android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
Description:

java.lang.RuntimeException:Unable to create application com.stub.StubApp: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
--
2 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4730)
3 ......
4 Caused by:
5 android.database.sqlite.SQLiteDatabaseLockedException:database is locked (code 5)
6 android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
7 android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
8 android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
9 android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
10 android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1471)
11 com.evernote.android.job.JobStorage.store(JobStorage.java)
12 com.evernote.android.job.JobStorage.put(JobStorage.java)
13 com.evernote.android.job.JobManager.schedule(JobManager.java)
14 com.evernote.android.job.JobRequest.schedule(JobRequest.java)
15 com.android.app.job.onetime.ParamsJob.scheduleJob(ParamsJob.java)
16 com.android.app.job.core.JobManagerProxy.scheduleJob(JobManagerProxy.java)
17 com.android.app.job.core.JobManagerProxy.scheduleJobs(JobManagerProxy.java)
18 com.android.app.App.onCreate(App.java)
19 com.taobao.sophix.a.c.b(Sophix)
20 com.taobao.sophix.a.e.a(Sophix)
21 com.taobao.sophix.SophixApplication.onCreate(Sophix)
22 com.stub.StubApp.onCreate(SourceFile:120)
23 android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
24 android.app.ActivityThread.handleBindApplication(ActivityThread.java:4727)
25 android.app.ActivityThread.access$1600(ActivityThread.java:165)
26 android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
27 android.os.Handler.dispatchMessage(Handler.java:102)
28 android.os.Looper.loop(Looper.java:179)
29 android.app.ActivityThread.main(ActivityThread.java:5509)
30 java.lang.reflect.Method.invoke(Native Method)
31 java.lang.reflect.Method.invoke(Method.java:372)
32 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:961)
33 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by agrosner** [comment]
its quite possible you are accessing the DB on two different threads, though I am not seeing any DBFlow related code here.
