### ISSUE TITLE
SQLCipher with custom parameters

### ISSUE THREAD

**Issue by MGLaboratory** [agrosner/DBFlow#1691]
Hi!
Is it possible to open sqlcipher database with custom parameters?

I want to use simple algorithms & I need to set some pragma keys:
PRAGMA cipher_default_kdf_algorithm = PBKDF2_HMAC_SHA1;
PRAGMA cipher_hmac_algorithm = HMAC_SHA1;

Thanks in advance!

**Comment by agrosner** [comment]
in 5.0.0-alpha2, we have `onConfigure(db)` in the database callback, 

```kotlin
FlowManager.init(context) {
  database<MyCipherDatabase> {
    helperListener(helperListener)
  }
}

```

**Comment by agrosner** [comment]
use that method to set pragmas.
