### ISSUE TITLE
multi-module multi-db support in one application

### ISSUE THREAD

**Issue by muhammadzadeh** [agrosner/DBFlow#1694]
# ISSUE\_TEMPLATE

DBFlow Version: 4.2.4

Bug or Feature Request:

Description:
hi guys 
please help for this
i have a app that contain 5 modules that each module is standalone (development and usage),
each module contain its database and cipher with different cipher-key,
some modules database not encrypted.

**Comment by agrosner** [comment]
even though this is 5.0, this still applies https://dbflow.gitbook.io/dbflow/v/develop/usage2/advanced-usage/multiplemodules
The type of db is determined at the database level. You just need to init all of it. not sure what else i can provide to help 👍
