### ISSUE TITLE
what’s the differences between 'com.github.agrosner.dbflow' and 'com.github.Raizlabs.dbflow'

### ISSUE THREAD

**Issue by wellcao** [agrosner/DBFlow#1697]
and i can not find dbflow created by Raizlabs in github

**Comment by sanxy** [comment]
The library name has been changed from 'com.github.agrosner.dbflow' to 'com.github.Raizlabs.dbflow'. You can read the [latest release here](https://github.com/agrosner/DBFlow/releases) where it was stated. The project was maintained by another account initially.
