### ISSUE TITLE
Is there a way to know migration is completed

### ISSUE THREAD

**Issue by nithin-aktivolabs** [agrosner/DBFlow#1702]
# Is there a way to know migration is completed

DBFlow Version: 4.1.2

Feature Request: Migration callback

Description: 
I have a DB and run an initial database set up in version 0. Now, my scenario is, I want to notify once the migration is completed. Is there any way in DBFlow to see the migration is completed?

**Comment by agrosner** [comment]
You can use the `onPostMigration` method on your migration class. or  in the body of the `migrate` method and just use a stream or event bus to notify subscribers. There isn't a notification system for migrations built into DBFlow.

**Comment by nithin-aktivolabs** [comment]
thanks aGrosner
