### ISSUE TITLE
must be a visible abstract class that extends com.dbflow5.config.DBFlowDatabase

### ISSUE THREAD

**Issue by tianyingzhong** [agrosner/DBFlow#1705]
# ISSUE\_TEMPLATE

DBFlow Version:5.0.0-alpha1

Bug or Feature Request:

Description:
**studio 版本 4.0.1  gradle 版本 6.1.1** 

AppDataBase为新建的一个数据库类

AppDataBase must be a visible abstract class that extends com.dbflow5.config.DBFlowDatabase*==========*
����: java.lang.Thread.getStackTrace(Thread.java:1559)
����: com.dbflow5.processor.ProcessorManager.logError(ProcessorManager.kt:212)
����: com.dbflow5.processor.ProcessorManager.logError(ProcessorManager.kt:219)
����: com.dbflow5.processor.definition.DatabaseDefinition.<init>(DatabaseDefinition.kt:82)
����: com.dbflow5.processor.DatabaseHandler.onProcessElement(Handlers.kt:229)
����: com.dbflow5.processor.BaseContainerHandler.handle(Handlers.kt:194)
����: com.dbflow5.processor.ProcessorManager.handle(ProcessorManager.kt:233)
����: com.dbflow5.processor.DBFlowProcessor.process(DBFlowProcessor.kt:67)
����: �����������һ��ѭ���д���������Ϊ 'com.dbflow5.config.AppDataBaseAppDataBase_Database' ���ļ�����ע�ʹ���
9 ������
4 ������

> Task :app:processDebugResources

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':module_arrival:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by TzuChiangLi** [comment]
meet the problem,too

**Comment by agrosner** [comment]
Im pretty sure the error explains itself. `AppDataBase must be a visible abstract class that extends com.dbflow5.config.DBFlowDatabase` https://dbflow.gitbook.io/dbflow/v/develop/usage2/gettingstarted#creating-a-database
