### ISSUE TITLE
How to add condition for Method

### ISSUE THREAD

**Issue by Momohanfeng** [agrosner/DBFlow#1706]
# ISSUE\_TEMPLATE

DBFlow Version:
all versions
Bug or Feature Request:
Feature
Description:
I want to excute sql code like 
`select max(timeStamp), count(isRead = 1 or null) as unRead, * from MessageInfo group by userId`

but the Method.count or other function only accept IProperty, how to implement the sql on DBFlow? thanks

**Comment by agrosner** [comment]
```SQL
select max(timeStamp), count(isRead = 1 or null) as unRead, * from MessageInfo group by userId
```
something like this?
```kotlin
select(max(timeStamp), count(propertyString("isRead = 1 or NULL")).as("unRead"), Property.ALL_PROPERTY) from MessageInfo::class groupBy MessageInfo.userId
```
