### ISSUE TITLE
Building error after migrate AndroidX annotation processors are not incremental: jetified-dbflow-processor-4.1.2.jar 

### ISSUE THREAD

**Issue by emmacr86** [agrosner/DBFlow#1708]
# ISSUE\_TEMPLATE

DBFlow Version: 4.1.2

Bug or Feature Request: Building error after migrate AndroidX

Description: Does anyone know how to fix the next error? It occurs every time when I build the project

> Task :app:compileDevDebugJavaWithJavac
The following annotation processors are not incremental: jetified-dbflow-processor-4.1.2.jar (com.github.Raizlabs.DBFlow:dbflow-processor:4.1.2).
Make sure all annotation processors are incremental to improve your build speed.

My gradle is: 

apply plugin: 'com.android.application'
def dbflow_version = "4.1.2"

android {
    compileSdkVersion 30
    defaultConfig {
        applicationId 'com.iscdeveloper.btlvisor_cp'
        minSdkVersion 17
        targetSdkVersion 30
        versionCode 50
        versionName '5.1.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        multiDexEnabled true
    }

    lintOptions { checkReleaseBuilds false }
    dexOptions {
        javaMaxHeapSize "2048M"
    }
    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    flavorDimensions "device"
    productFlavors {
    }

    packagingOptions {
        exclude 'META-INF/rxjava.properties'
    }

    productFlavors {
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.constraintlayout:constraintlayout:2.0.1'
    testImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation project(':library')
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.gms:play-services-base:17.4.0'
    implementation 'com.google.android.gms:play-services-location:17.1.0'
    implementation 'com.google.android.gms:play-services-ads:19.4.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'
    implementation 'androidx.recyclerview:recyclerview:1.1.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.google.android.material:material:1.2.1'
    implementation 'com.squareup.retrofit:retrofit:1.9.0'
    implementation 'com.squareup.okhttp3:okhttp:4.7.2'
    annotationProcessor "com.github.Raizlabs.DBFlow:dbflow-processor:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-core:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow:${dbflow_version}"
    implementation "com.github.Raizlabs.DBFlow:dbflow-rx2:${dbflow_version}"
    implementation 'io.reactivex:rxandroid:1.2.1'
    implementation 'io.reactivex:rxjava:1.2.7'
    implementation 'com.joanzapata.iconify:android-iconify-fontawesome:2.2.2'
    implementation 'com.joanzapata.iconify:android-iconify-material-community:2.2.2'
    implementation 'org.sufficientlysecure:html-textview:3.5'
    implementation 'com.github.bumptech.glide:glide:4.9.0'
    implementation 'com.github.clans:fab:1.6.4'
    implementation 'de.hdodenhof:circleimageview:2.2.0'
    implementation 'com.p_v:flexiblecalendar:1.2.1'
    testImplementation 'junit:junit:4.12'
    implementation project(':expandablerecyclerview')
    implementation 'io.nlopez.smartlocation:library:3.3.3'
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1'
    // Searchable spinner repository
}

**Comment by agrosner** [comment]
youll need to update to 5.0.0-alpha2 or up (when its released). incremental support for annotation processors was just added.
