### ISSUE TITLE
DBFlow 5.0 - lack of documentation

### ISSUE THREAD

**Issue by rehovicova** [agrosner/DBFlow#1711]
I came here after I found out the package name changed. There is nearly no documentation on how to even instantiate DBFlow 5.0. Most of the links point to DBFlow < 5.0, the code was updated 2 years ago... Is it even still supported?

**Comment by Nailik** [comment]
I don't think there is any ongoing work. There are several issues about this since years, you should go maybe for room or sth else.

**Comment by agrosner** [comment]
Im in process of updating the documentation [here](https://dbflow.gitbook.io/dbflow/v/develop/)
