### ISSUE TITLE
Select query not running against content provider

### ISSUE THREAD

**Issue by dwaynehoy** [agrosner/DBFlow#912]
Version 3.1.1

I've setup a table which is based against a content provider (Required for sync adapter)
However I've noticed that any select queries are not run against the content provider but the database directly, this is causing some very weird bugs. 

i.e. 

With the following table definition

```
@ModelContainer
@TableEndpoint(name = UserFavorites.NAME, contentProvider = Database.class)
@Table(database = Database.class, name = UserFavorites.NAME, uniqueColumnGroups = {@UniqueGroup( groupNumber = 1)})
public class UserFavorites  extends BaseProviderModel<UserFavorites> {
    public static final String NAME = "user_favorites";
    @ContentUri(path = NAME, type = ContentUri.ContentType.VND_MULTIPLE + NAME)
    public static final Uri CONTENT_URI = ContentUtils.buildUri(Database.BASE_CONTENT_URI, Database.AUTHORITY, NAME); 

...

}
```

A query like this:

```
List<UserFavorites> userFavorites = SQLite.select()
                .from(UserFavorites.class)
                .where(UserFavorites_Table.sync_status.notEq(SyncAdapter.SYNC_STATUS_FAILED))
                .and(UserFavorites_Table.sync_status.notEq(SyncAdapter.SYNC_STATUS_COMPLETE))
                .queryList();
```

Eventually calls the framework code
-  return getRetrievalAdapter().getListModelLoader().load(query);
-  return load(getDatabaseDefinition().getWritableDatabase(), query);
- ...
-  final Cursor cursor = databaseWrapper.rawQuery(query, null);

Which bypasses the content provider and queries the database directly. It would be nice if the query framework supported pulling data from content providers where the table is backed by a content provider.

**Comment by agrosner** [comment]
closing as this is not supported.
